<a href="https://colab.research.google.com/github/cracker38/AgriLoss-Value-Intelligence-Rwanda/blob/main/NISR_2026_Agri_Productivity_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Project Objective
2. Data Sources
3. Import Libraries
4. Load Dataset
5. Data Understanding
6. Data Cleaning
7. Exploratory Data Analysis
8. Feature Engineering
9. Machine Learning
10. Model Evaluation
11. Conclusions

## 2. Data Sources

The primary data source for this project is the **Rwanda Seasonal Agricultural Survey (SAS) 2024**, provided by the **National Institute of Statistics of Rwanda (NISR)**.

The dataset covers three agricultural seasons:

- **Season A**
- **Season B**
- **Season C**

For each agricultural season, four categories of datasets are available:

1. **Production**
2. **Agricultural Practice**
3. **Fertilizer and Pesticide**
4. **Screening**

Therefore, the project uses **12 JSON datasets** covering agricultural production, farming practices, agricultural inputs, and screening information across Rwanda.

The datasets will be analyzed to identify patterns and relationships that can support agricultural productivity analysis and data-driven decision-making.

In [1]:
import os
import requests

# Google Drive is already mounted
dataset_path = "/content/drive/MyDrive/NISR_Hackathon/datasets"

# Create the folder if needed
os.makedirs(dataset_path, exist_ok=True)

# Your 12 Google Drive files
files = {
    "sas_2024_seasonA_agricultural_practice.json":
        "1uxhFqOhl9rGBDvWeH3f_odDn3ky7hdqs",

    "sas_2024_seasonA_fertilizer_pesticide.json":
        "1i-eF5L3aJ7iO_J4574_XMNr611DWGl-V",

    "sas_2024_seasonA_production.json":
        "11mujUOSPjCsVCA9HFSpiGT0qDq3b6tJ_",

    "sas_2024_seasonA_screening.json":
        "1mZW1V-e398svmN0eczGYdNNGud-cmDI-",

    "sas_2024_seasonB_agricultural_practice.json":
        "16lzKLqSTI1LDKtEmSIgYRgqB4tvtIkqf",

    "sas_2024_seasonB_fertilizer_pesticide.json":
        "1z_v6tnv0jHUXj1A4EilaOI-2HL1iT7z0",

    "sas_2024_seasonB_production.json":
        "1DNqf3JBgC_A3atCod9ZF0xe_kg5L_Mi8",

    "sas_2024_seasonB_screening.json":
        "1c3gcsqc4XiJ5clImRppLOKHEWtXAvgpX",

    "sas_2024_seasonC_agricultural_practice.json":
        "1DNgFsT3Tc-p6e1-o1bopefN1bpTCK6jX",

    "sas_2024_seasonC_fertilizer_pesticide.json":
        "1I-BSuQko4dPG0HTI_FOSmH4LIdXWbCfK",

    "sas_2024_seasonC_production.json":
        "14gLbOkGS4KMM3NytVRg5tuYMPeCWlY4j",

    "sas_2024_seasonC_screening.json":
        "1JvWCi3wkfp5HvnvUVEIETzICgrZVh_eC"
}

# Download files
for filename, file_id in files.items():

    destination = os.path.join(dataset_path, filename)

    print(f"Downloading: {filename}")

    url = f"https://drive.google.com/uc?export=download&id={file_id}"

    response = requests.get(url)

    if response.status_code == 200:
        with open(destination, "wb") as f:
            f.write(response.content)

        print("   ✅ Saved")
    else:
        print(f"   ❌ Failed: HTTP {response.status_code}")

# Verify
print("\n===================================")
print("CHECKING DATASETS")
print("===================================")

json_files = [
    file for file in os.listdir(dataset_path)
    if file.lower().endswith(".json")
]

print(f"\nTotal JSON datasets: {len(json_files)}")

for i, file in enumerate(sorted(json_files), 1):
    print(f"{i}. {file}")

Downloading: sas_2024_seasonA_agricultural_practice.json
   ✅ Saved
Downloading: sas_2024_seasonA_fertilizer_pesticide.json
   ✅ Saved
Downloading: sas_2024_seasonA_production.json
   ✅ Saved
Downloading: sas_2024_seasonA_screening.json
   ✅ Saved
Downloading: sas_2024_seasonB_agricultural_practice.json
   ✅ Saved
Downloading: sas_2024_seasonB_fertilizer_pesticide.json
   ✅ Saved
Downloading: sas_2024_seasonB_production.json
   ✅ Saved
Downloading: sas_2024_seasonB_screening.json
   ✅ Saved
Downloading: sas_2024_seasonC_agricultural_practice.json
   ✅ Saved
Downloading: sas_2024_seasonC_fertilizer_pesticide.json
   ✅ Saved
Downloading: sas_2024_seasonC_production.json
   ✅ Saved
Downloading: sas_2024_seasonC_screening.json
   ✅ Saved

===================================
CHECKING DATASETS
===================================

Total JSON datasets: 12
1. sas_2024_seasonA_agricultural_practice.json
2. sas_2024_seasonA_fertilizer_pesticide.json
3. sas_2024_seasonA_production.json
4. sas_2024_seasonA_screening.json
5. sas_2024_seasonB_agricultural_practice.json
6. sas_2024_seasonB_fertilizer_pesticide.json
7. sas_2024_seasonB_production.json
8. sas_2024_seasonB_screening.json
9. sas_2024_seasonC_agricultural_practice.json
10. sas_2024_seasonC_fertilizer_pesticide.json
11. sas_2024_seasonC_production.json
12. sas_2024_seasonC_screening.json

In [ ]:
# ============================================
# 3. IMPORT LIBRARIES
# ============================================

import os
import json
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from IPython.display import display

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
# ============================================
# 4. CHECK UPLOADED DATASETS
# ============================================

import os

# Path to the datasets stored in Google Drive
dataset_path = "/content/drive/MyDrive/NISR_Hackathon/datasets"

# Get all JSON files
json_files = [
    file for file in os.listdir(dataset_path)
    if file.lower().endswith(".json")
]

# Display number of datasets
print(f"Number of JSON files found: {len(json_files)}")
print()

# Display dataset names
for i, file in enumerate(sorted(json_files), start=1):
    print(f"{i}. {file}")

Number of JSON files found: 12

1. sas_2024_seasonA_agricultural_practice.json
2. sas_2024_seasonA_fertilizer_pesticide.json
3. sas_2024_seasonA_production.json
4. sas_2024_seasonA_screening.json
5. sas_2024_seasonB_agricultural_practice.json
6. sas_2024_seasonB_fertilizer_pesticide.json
7. sas_2024_seasonB_production.json
8. sas_2024_seasonB_screening.json
9. sas_2024_seasonC_agricultural_practice.json
10. sas_2024_seasonC_fertilizer_pesticide.json
11. sas_2024_seasonC_production.json
12. sas_2024_seasonC_screening.json

In [4]:

# ============================================================
# NISR 2026 BIG DATA HACKATHON
# DATASET SETUP AND VALIDATION
# Download only missing or invalid datasets
# ============================================================

import os
import json
import google.auth

from google.colab import drive, auth
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
from IPython.display import display

# ============================================================
# 1. GOOGLE DRIVE MOUNT — HANDLE EXISTING MOUNT POINTS
# ============================================================

def mount_google_drive():
    """Reuse an existing Drive mount or select an available mount point."""

    mount_points = [
        "/content/drive",
        "/content/gdrive"
    ]

    # Reuse Drive if it is already mounted at either location
    for point in mount_points:
        if os.path.ismount(point):
            if os.path.isdir(os.path.join(point, "MyDrive")):
                print(f"Google Drive already mounted: {point}")
                return point

    # Otherwise, select a mount point that is not occupied
    for point in mount_points:
        if not os.path.lexists(point):
            os.makedirs(point, exist_ok=True)
            drive.mount(point, force_remount=False)

            if os.path.isdir(os.path.join(point, "MyDrive")):
                print(f"Google Drive mounted successfully: {point}")
                return point

        elif os.path.isdir(point) and not os.listdir(point):
            drive.mount(point, force_remount=False)

            if os.path.isdir(os.path.join(point, "MyDrive")):
                print(f"Google Drive mounted successfully: {point}")
                return point

    raise RuntimeError(
        "Could not identify an available Google Drive mount point. "
        "Check the current Colab runtime before attempting a remount."
    )


MOUNT_POINT = mount_google_drive()

# ============================================================
# 2. CONFIGURE THE PERSISTENT DATASET DIRECTORY
# ============================================================

DATASET_PATH = os.path.join(
    MOUNT_POINT,
    "MyDrive",
    "M Training Deliverables",
    "NISR_Hackathon",
    "datasets"
)

os.makedirs(DATASET_PATH, exist_ok=True)

print("\n" + "=" * 75)
print("NISR DATASET CONFIGURATION")
print("=" * 75)
print("Storage:", DATASET_PATH)

# ============================================================
# 3. DATASET MANIFEST — 12 SAS 2024 JSON FILES
# ============================================================

FILES = {
    "sas_2024_seasonA_agricultural_practice.json":
        "1uxhFqOhl9rGBDvWeH3f_odDn3ky7hdqs",

    "sas_2024_seasonA_fertilizer_pesticide.json":
        "1i-eF5L3aJ7iO_J4574_XMNr611DWGl-V",

    "sas_2024_seasonA_production.json":
        "11mujUOSPjCsVCA9HFSpiGT0qDq3b6tJ_",

    "sas_2024_seasonA_screening.json":
        "1mZW1V-e398svmN0eczGYdNNGud-cmDI-",

    "sas_2024_seasonB_agricultural_practice.json":
        "16lzKLqSTI1LDKtEmSIgYRgqB4tvtIkqf",

    "sas_2024_seasonB_fertilizer_pesticide.json":
        "1z_v6tnv0jHUXj1A4EilaOI-2HL1iT7z0",

    "sas_2024_seasonB_production.json":
        "1DNqf3JBgC_A3atCod9ZF0xe_kg5L_Mi8",

    "sas_2024_seasonB_screening.json":
        "1c3gcsqc4XiJ5clImRppLOKHEWtXAvgpX",

    "sas_2024_seasonC_agricultural_practice.json":
        "1DNgFsT3Tc-p6e1-o1bopefN1bpTCK6jX",

    "sas_2024_seasonC_fertilizer_pesticide.json":
        "1I-BSuQko4dPG0HTI_FOSmH4LIdXWbCfK",

    "sas_2024_seasonC_production.json":
        "14gLbOkGS4KMM3NytVRg5tuYMPeCWlY4j",

    "sas_2024_seasonC_screening.json":
        "1JvWCi3wkfp5HvnvUVEIETzICgrZVh_eC",
}

# ============================================================
# 4. VALIDATE EXISTING JSON FILES
# ============================================================

def is_valid_json(path):
    """Return True only when the file exists and parses as JSON."""

    try:
        if not os.path.isfile(path):
            return False

        if os.path.getsize(path) == 0:
            return False

        with open(path, "r", encoding="utf-8-sig") as file:
            json.load(file)

        return True

    except (ValueError, OSError, UnicodeError):
        return False


# ============================================================
# 5. CHECK WHICH FILES NEED DOWNLOADING
# ============================================================

files_to_download = {
    filename: file_id
    for filename, file_id in FILES.items()
    if not is_valid_json(os.path.join(DATASET_PATH, filename))
}

valid_existing = len(FILES) - len(files_to_download)

print(f"\nExpected datasets: {len(FILES)}")
print(f"Already valid:     {valid_existing}")
print(f"Need downloading:  {len(files_to_download)}")

# ============================================================
# 6. DOWNLOAD ONLY MISSING OR INVALID FILES
# ============================================================

if not files_to_download:

    print("\nSUCCESS: All 12 datasets are already valid.")
    print("No downloads required.")

else:
    print("\nThe following datasets need attention:")
    for filename in files_to_download:
        print(" -", filename)

    auth.authenticate_user()

    credentials, _ = google.auth.default()
    drive_service = build(
        "drive",
        "v3",
        credentials=credentials,
        cache_discovery=False
    )

    for filename, file_id in files_to_download.items():

        destination = os.path.join(DATASET_PATH, filename)
        temporary_path = destination + ".download"

        try:
            print(f"\nProcessing: {filename}")

            request = drive_service.files().get_media(
                fileId=file_id
            )

            with open(temporary_path, "wb") as output_file:

                downloader = MediaIoBaseDownload(
                    output_file,
                    request,
                    chunksize=1024 * 1024
                )

                done = False

                while not done:
                    status, done = downloader.next_chunk()

                    if status:
                        print(
                            f"  Download progress: "
                            f"{status.progress() * 100:.1f}%"
                        )

            # Validate the downloaded file before replacing anything
            if not is_valid_json(temporary_path):
                raise ValueError(
                    "Downloaded content is not valid JSON. "
                    "Check the Drive file ID and access permissions."
                )

            # Replace the destination only after validation succeeds
            os.replace(temporary_path, destination)

            print(f"SUCCESS: {filename}")

        except Exception as error:

            if os.path.exists(temporary_path):
                os.remove(temporary_path)

            print(f"FAILED: {filename}")
            print(f"Reason: {error}")

# ============================================================
# 7. FINAL DATASET VERIFICATION
# ============================================================

verification = []

for filename in FILES:
    file_path = os.path.join(DATASET_PATH, filename)
    valid = is_valid_json(file_path)

    verification.append({
        "Dataset": filename,
        "Status": "VALID" if valid else "MISSING / INVALID",
        "Size (MB)": (
            round(os.path.getsize(file_path) / (1024 ** 2), 2)
            if valid else None
        )
    })

verification_df = pd.DataFrame(verification) if False else None

# Create the verification table without requiring pandas
print("\n" + "=" * 75)
print("FINAL VERIFICATION")
print("=" * 75)

for item in verification:
    print(f"{item['Status']:<20} {item['Dataset']}")

valid_count = sum(
    item["Status"] == "VALID"
    for item in verification
)

print(f"\nVerified datasets: {valid_count}/{len(FILES)}")
print(f"Persistent storage: {DATASET_PATH}")

if valid_count == len(FILES):
    print("\nREADY: Proceed to Data Understanding.")
else:
    print(
        "\nWARNING: Some datasets are still missing or invalid. "
        "Review the errors above before continuing."
    )

Mounted at /content/gdrive
Google Drive mounted successfully: /content/gdrive

===========================================================================
NISR DATASET CONFIGURATION
===========================================================================
Storage: /content/gdrive/MyDrive/M Training Deliverables/NISR_Hackathon/datasets

Expected datasets: 12
Already valid:     12
Need downloading:  0

SUCCESS: All 12 datasets are already valid.
No downloads required.

===========================================================================
FINAL VERIFICATION
===========================================================================
VALID                sas_2024_seasonA_agricultural_practice.json
VALID                sas_2024_seasonA_fertilizer_pesticide.json
VALID                sas_2024_seasonA_production.json
VALID                sas_2024_seasonA_screening.json
VALID                sas_2024_seasonB_agricultural_practice.json
VALID                sas_2024_seasonB_fertilizer_pesticide.json
VALID                sas_2024_seasonB_production.json
VALID                sas_2024_seasonB_screening.json
VALID                sas_2024_seasonC_agricultural_practice.json
VALID                sas_2024_seasonC_fertilizer_pesticide.json
VALID                sas_2024_seasonC_production.json
VALID                sas_2024_seasonC_screening.json

Verified datasets: 12/12
Persistent storage: /content/gdrive/MyDrive/M Training Deliverables/NISR_Hackathon/datasets

READY: Proceed to Data Understanding.

In [5]:

# ============================================================
# 5. DATA UNDERSTANDING — NISR 2026 BIG DATA HACKATHON
# Read existing datasets only; NO DOWNLOADS
# ============================================================

import os
import json
import pandas as pd
from IPython.display import display

DATASET_PATH = (
    "/content/gdrive/MyDrive/M Training Deliverables/"
    "NISR_Hackathon/datasets"
)

FILES = [
    f"sas_2024_season{s}_{category}.json"
    for s in ["A", "B", "C"]
    for category in [
        "agricultural_practice",
        "fertilizer_pesticide",
        "production",
        "screening"
    ]
]

datasets = {}
summary = []
errors = []

# ------------------------------------------------------------
# 1. LOAD EXISTING DATASETS
# ------------------------------------------------------------

for filename in FILES:
    path = os.path.join(DATASET_PATH, filename)

    print("\n" + "=" * 85)
    print(f"DATASET: {filename}")
    print("=" * 85)

    try:
        if not os.path.isfile(path):
            raise FileNotFoundError(
                "File is missing. Run the setup cell if necessary."
            )

        with open(path, "r", encoding="utf-8-sig") as file:
            raw_data = json.load(file)

        if isinstance(raw_data, list):
            df = pd.json_normalize(raw_data)

        elif isinstance(raw_data, dict):
            record_key = next(
                (
                    key for key in ("data", "results", "records", "items")
                    if isinstance(raw_data.get(key), list)
                ),
                None
            )

            df = (
                pd.json_normalize(raw_data[record_key])
                if record_key
                else pd.json_normalize(raw_data)
            )

        else:
            raise ValueError("Unsupported JSON structure.")

        name = filename.removesuffix(".json")
        datasets[name] = df

        rows, columns = df.shape
        missing = int(df.isna().sum().sum())
        duplicates = int(df.duplicated().sum())
        memory_mb = df.memory_usage(deep=True).sum() / (1024 ** 2)

        print(f"Rows: {rows:,} | Columns: {columns:,}")
        print(f"Missing cells: {missing:,}")
        print(f"Duplicate rows: {duplicates:,}")
        print(f"Memory usage: {memory_mb:.2f} MB")

        # Column information
        print("\nCOLUMN INFORMATION")
        column_info = pd.DataFrame({
            "Column": df.columns.astype(str),
            "Data Type": df.dtypes.astype(str).values,
            "Missing Values": df.isna().sum().values,
            "Missing (%)": (
                (df.isna().mean() * 100).round(2).values
            )
        })
        display(column_info)

        # Preview
        print("\nFIRST FIVE RECORDS")
        display(df.head())

        # Numerical statistics
        print("\nNUMERICAL SUMMARY")
        numeric = df.select_dtypes(include="number")

        if not numeric.empty:
            display(numeric.describe().T)
        else:
            print("No numerical columns detected.")

        # Summary record
        summary.append({
            "Dataset": filename,
            "Rows": rows,
            "Columns": columns,
            "Missing Cells": missing,
            "Duplicate Rows": duplicates,
            "Memory (MB)": round(memory_mb, 2)
        })

    except Exception as error:
        errors.append({
            "Dataset": filename,
            "Error": str(error)
        })
        print(f"ERROR: {error}")

# ------------------------------------------------------------
# 2. OVERALL SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 85)
print("OVERALL DATA UNDERSTANDING SUMMARY")
print("=" * 85)

summary_df = pd.DataFrame(summary)

if not summary_df.empty:
    display(summary_df)

    print(f"Datasets loaded: {len(datasets)}/{len(FILES)}")
    print(f"Total rows: {summary_df['Rows'].sum():,}")
    print(f"Total columns: {summary_df['Columns'].sum():,}")
    print(f"Total missing cells: {summary_df['Missing Cells'].sum():,}")
    print(f"Total duplicate rows: {summary_df['Duplicate Rows'].sum():,}")
    print(
        f"Combined DataFrame memory: "
        f"{summary_df['Memory (MB)'].sum():.2f} MB"
    )

if errors:
    print("\nDATASETS REQUIRING ATTENTION")
    display(pd.DataFrame(errors))
else:
    print("\nAll 12 datasets were loaded successfully.")

print("\nData Understanding completed. No downloads were performed.")

=====================================================================================
DATASET: sas_2024_seasonA_agricultural_practice.json
=====================================================================================
Rows: 17,506 | Columns: 59
Missing cells: 0
Duplicate rows: 0
Memory usage: 51.17 MB

COLUMN INFORMATION

         Column Data Type  Missing Values  Missing (%)
0            id    object               0          0.0
1    Segment_ID    object               0          0.0
2          s1q1    object               0          0.0
3          s1q2    object               0          0.0
4          s1q3    object               0          0.0
5          s1q4    object               0          0.0
6          s1q6    object               0          0.0
7          s1q7    object               0          0.0
8          s1q8    object               0          0.0
9          s1q9    object               0          0.0
10        s1q14    object               0          0.0
11        s1q17    object               0          0.0
12      s1q17_o    object               0          0.0
13         s2q1    object               0          0.0
14         s2q2    object               0          0.0
15      s2q2_ha    object               0          0.0
16         s4q1    object               0          0.0
17         s4q2    object               0          0.0
18         s4q3    object               0          0.0
19         s4q4    object               0          0.0
20         s4q5    object               0          0.0
21         s4q6    object               0          0.0
22       s4q7_1    object               0          0.0
23       s4q7_2    object               0          0.0
24       s4q7_3    object               0          0.0
25       s4q7_4    object               0          0.0
26         s4q8    object               0          0.0
27         s4q9    object               0          0.0
28      s4q10_1    object               0          0.0
29    s4q10_2_1    object               0          0.0
30    s4q10_2_2    object               0          0.0
31    s4q10_2_3    object               0          0.0
32    s4q10_2_4    object               0          0.0
33      s4q10_3    object               0          0.0
34      s4q11_1    object               0          0.0
35    s4q11_2_1    object               0          0.0
36    s4q11_2_2    object               0          0.0
37    s4q11_2_3    object               0          0.0
38    s4q11_2_4    object               0          0.0
39    s4q11_2_5    object               0          0.0
40      s4q11_3    object               0          0.0
41      s4q12_1    object               0          0.0
42    s4q12_2_1    object               0          0.0
43    s4q12_2_2    object               0          0.0
44    s4q12_2_3    object               0          0.0
45      s4q12_3    object               0          0.0
46      s4q12_4    object               0          0.0
47        s4q13    object               0          0.0
48        s4q14    object               0          0.0
49        s4q15    object               0          0.0
50        s4q16    object               0          0.0
51      s4q17_1    object               0          0.0
52      s4q17_2    object               0          0.0
53      s4q17_3    object               0          0.0
54      s4q18_1    object               0          0.0
55      s4q18_2    object               0          0.0
56      s4q18_3    object               0          0.0
57        s4q19    object               0          0.0
58  plot_weight    object               0          0.0

FIRST FIVE RECORDS

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q8,s1q9,...,s4q15,s4q16,s4q17_1,s4q17_2,s4q17_3,s4q18_1,s4q18_2,s4q18_3,s4q19,plot_weight
0,1,111003,Kigali,Nyarugenge,Agricultural land on hillside,3,20,Small scale farmer as individual,Male,55,...,,,,,,,,,,132.1108
1,2,111004,Kigali,Nyarugenge,Agricultural land on hillside,4,7,Small scale farmer as individual,Male,34,...,,,,,,,,,,326.3918
2,3,111007,Kigali,Nyarugenge,Agricultural land on hillside,7,23,Small scale farmer as individual,Female,64,...,,,,,,,,,,61.6604
3,4,114019,Kigali,Nyarugenge,Mixed,19,23,Small scale farmer as individual,Male,40,...,,,,,,,,,,1023.222
4,5,114019,Kigali,Nyarugenge,Mixed,19,1,Small scale farmer as individual,Male,64,...,,,,,,,,,,73.48241

NUMERICAL SUMMARY
No numerical columns detected.

=====================================================================================
DATASET: sas_2024_seasonA_fertilizer_pesticide.json
=====================================================================================
Rows: 22,105 | Columns: 64
Missing cells: 0
Duplicate rows: 0
Memory usage: 70.24 MB

COLUMN INFORMATION

        Column Data Type  Missing Values  Missing (%)
0           id    object               0          0.0
1   Segment_ID    object               0          0.0
2         s1q1    object               0          0.0
3         s1q2    object               0          0.0
4         s1q3    object               0          0.0
..         ...       ...             ...          ...
59    s3q20_o4    object               0          0.0
60      s3q214    object               0          0.0
61      s3q224    object               0          0.0
62      s3q234    object               0          0.0
63      s3q244    object               0          0.0

[64 rows x 4 columns]

FIRST FIVE RECORDS

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q8,s1q9,...,s3q213,s3q223,s3q233,s3q243,s3q204,s3q20_o4,s3q214,s3q224,s3q234,s3q244
0,1,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,1,Large scale farmer as individual,Male,64,...,,,,,,,,,,
1,2,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,1,Large scale farmer as individual,Male,64,...,,,,,,,,,,
2,3,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,1,Large scale farmer as individual,Male,64,...,,,,,,,,,,
3,4,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,1,Large scale farmer as individual,Male,64,...,,,,,,,,,,
4,5,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,1,Large scale farmer as individual,Male,64,...,,,,,,,,,,

NUMERICAL SUMMARY
No numerical columns detected.

=====================================================================================
DATASET: sas_2024_seasonA_production.json
=====================================================================================
Rows: 39,330 | Columns: 96
Missing cells: 0
Duplicate rows: 0
Memory usage: 189.79 MB

COLUMN INFORMATION

         Column Data Type  Missing Values  Missing (%)
0            id    object               0          0.0
1    Segment_ID    object               0          0.0
2          s1q1    object               0          0.0
3          s1q2    object               0          0.0
4          s1q3    object               0          0.0
..          ...       ...             ...          ...
91      s4q12_1    object               0          0.0
92        s4q14    object               0          0.0
93        s4q15    object               0          0.0
94        s5q12    object               0          0.0
95  plot_weight    object               0          0.0

[96 rows x 4 columns]

FIRST FIVE RECORDS

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q8,s1q9,...,s4q6,s4q8,s4q9,s4q10_1,s4q11_1,s4q12_1,s4q14,s4q15,s5q12,plot_weight
0,1,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,1,Large scale farmer as individual,Male,64,...,No,Yes,No,,,,No,,01/03/2024,1
1,2,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,1,Large scale farmer as individual,Male,64,...,Yes,Yes,Yes,No,Yes,No,No,,01/03/2024,1
2,3,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,1,Large scale farmer as individual,Male,64,...,No,Yes,Yes,No,Yes,No,No,,01/03/2024,1
3,4,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,1,Large scale farmer as individual,Male,64,...,No,Yes,Yes,No,No,No,No,,01/03/2024,1
4,5,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,1,Large scale farmer as individual,Male,64,...,No,Yes,Yes,No,Yes,No,No,,01/03/2024,1

NUMERICAL SUMMARY
No numerical columns detected.

=====================================================================================
DATASET: sas_2024_seasonA_screening.json
=====================================================================================
Rows: 54,382 | Columns: 46
Missing cells: 0
Duplicate rows: 0
Memory usage: 129.63 MB

COLUMN INFORMATION

          Column Data Type  Missing Values  Missing (%)
0             id    object               0          0.0
1     Segment_ID    object               0          0.0
2           s1q1    object               0          0.0
3           s1q2    object               0          0.0
4           s1q3    object               0          0.0
5           s1q4    object               0          0.0
6         s1q5_2    object               0          0.0
7          s1q10    object               0          0.0
8          s1q13    object               0          0.0
9           s2q1    object               0          0.0
10          s2q2    object               0          0.0
11          s2q3    object               0          0.0
12          s2q4    object               0          0.0
13     s2q5_bloc    object               0          0.0
14          s2q5    object               0          0.0
15          s2q6    object               0          0.0
16          s2q7    object               0          0.0
17    s2q7_Other    object               0          0.0
18          s2q8    object               0          0.0
19        s2q9_1    object               0          0.0
20        s2q9_2    object               0          0.0
21        s2q9_3    object               0          0.0
22        s2q9_o    object               0          0.0
23         s2q10    object               0          0.0
24       s2q11_1    object               0          0.0
25       s2q11_2    object               0          0.0
26       s2q11_3    object               0          0.0
27       s2q11_4    object               0          0.0
28       s2q11_o    object               0          0.0
29         s2q12    object               0          0.0
30         s2q13    object               0          0.0
31         s2q14    object               0          0.0
32          s3q1    object               0          0.0
33        s3q2_1    object               0          0.0
34        s3q2_2    object               0          0.0
35        s3q3_1    object               0          0.0
36        s3q3_2    object               0          0.0
37          s3q4    object               0          0.0
38          s3q5    object               0          0.0
39          s3q6    object               0          0.0
40          s3q7    object               0          0.0
41  CropCategory    object               0          0.0
42        s3q1_o    object               0          0.0
43   plot_weight    object               0          0.0
44  Plot_size_ha    object               0          0.0
45     crop_area    object               0          0.0

FIRST FIVE RECORDS

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q5_2,s1q10,s1q13,s2q1,...,s3q3_2,s3q4,s3q5,s3q6,s3q7,CropCategory,s3q1_o,plot_weight,Plot_size_ha,crop_area
0,1,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,1,...,91%100%,,Yes,Yes,Before 01/12,Fodder crops,,1,6.933567,6.933567
1,2,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,2,...,91%100%,,Yes,Yes,Between 01-15/01,Fodder crops,,1,33.87405,32.18035
2,3,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,2,...,91%100%,,Yes,Yes,Between 01-28/02,Fodder crops,,1,33.87405,33.87405
3,4,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,2,...,91%100%,,Yes,Yes,Between 01-28/02,Fodder crops,,1,33.87405,33.87405
4,5,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,2,...,91%100%,,Yes,Yes,Between 01-28/02,Fodder crops,,1,33.87405,33.87405

NUMERICAL SUMMARY
No numerical columns detected.

=====================================================================================
DATASET: sas_2024_seasonB_agricultural_practice.json
=====================================================================================
Rows: 17,261 | Columns: 53
Missing cells: 0
Duplicate rows: 0
Memory usage: 45.62 MB

COLUMN INFORMATION

         Column Data Type  Missing Values  Missing (%)
0            id    object               0          0.0
1    Segment_ID    object               0          0.0
2          s1q1    object               0          0.0
3          s1q2    object               0          0.0
4          s1q3    object               0          0.0
5          s1q4    object               0          0.0
6          s1q6    object               0          0.0
7          s1q7    object               0          0.0
8          s1q8    object               0          0.0
9          s1q9    object               0          0.0
10        s1q14    object               0          0.0
11        s1q17    object               0          0.0
12      s1q17_o    object               0          0.0
13         s2q1    object               0          0.0
14         s2q2    object               0          0.0
15      s2q2_ha    object               0          0.0
16         s4q1    object               0          0.0
17         s4q2    object               0          0.0
18         s4q3    object               0          0.0
19         s4q4    object               0          0.0
20         s4q5    object               0          0.0
21         s4q6    object               0          0.0
22       s4q7_1    object               0          0.0
23       s4q7_2    object               0          0.0
24       s4q7_3    object               0          0.0
25       s4q7_4    object               0          0.0
26         s4q8    object               0          0.0
27         s4q9    object               0          0.0
28      s4q10_1    object               0          0.0
29      s4q10_3    object               0          0.0
30      s4q11_1    object               0          0.0
31    s4q11_2_1    object               0          0.0
32    s4q11_2_2    object               0          0.0
33    s4q11_2_3    object               0          0.0
34    s4q11_2_4    object               0          0.0
35    s4q11_2_5    object               0          0.0
36      s4q11_3    object               0          0.0
37      s4q12_1    object               0          0.0
38      s4q12_3    object               0          0.0
39      s4q12_4    object               0          0.0
40        s4q13    object               0          0.0
41        s4q14    object               0          0.0
42        s4q15    object               0          0.0
43        s4q16    object               0          0.0
44      s4q17_1    object               0          0.0
45      s4q17_2    object               0          0.0
46      s4q17_3    object               0          0.0
47      s4q18_1    object               0          0.0
48      s4q18_2    object               0          0.0
49      s4q18_3    object               0          0.0
50      s4q18_4    object               0          0.0
51        s4q19    object               0          0.0
52  plot_weight    object               0          0.0

FIRST FIVE RECORDS

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q8,s1q9,...,s4q16,s4q17_1,s4q17_2,s4q17_3,s4q18_1,s4q18_2,s4q18_3,s4q18_4,s4q19,plot_weight
0,1,111007,Kigali,Nyarugenge,Agricultural land on hillside,7,7,Small scale farmer as individual,Female,67,...,,,,,,,,,,250.9704
1,2,114019,Kigali,Nyarugenge,Mixed,19,6,Small scale farmer as individual,Female,33,...,,,,,,,,,,730.6428
2,3,112018,Kigali,Nyarugenge,Agricultural land in marshland,18,1,Small scale farmer as individual,Male,55,...,,,,,,,,,,14.28061
3,4,111006,Kigali,Nyarugenge,Agricultural land on hillside,6,11,Small scale farmer as individual,Female,59,...,,,,,,,,,,348.2583
4,5,112016,Kigali,Nyarugenge,Agricultural land in marshland,16,20,Small scale farmer as individual,Male,51,...,,,,,,,,,,167.4533

NUMERICAL SUMMARY
No numerical columns detected.

=====================================================================================
DATASET: sas_2024_seasonB_fertilizer_pesticide.json
=====================================================================================
Rows: 19,965 | Columns: 64
Missing cells: 0
Duplicate rows: 0
Memory usage: 63.24 MB

COLUMN INFORMATION

         Column Data Type  Missing Values  Missing (%)
0            id    object               0          0.0
1    Segment_ID    object               0          0.0
2          s1q1    object               0          0.0
3          s1q2    object               0          0.0
4          s1q3    object               0          0.0
..          ...       ...             ...          ...
59       s3q214    object               0          0.0
60       s3q224    object               0          0.0
61       s3q234    object               0          0.0
62       s3q244    object               0          0.0
63  plot_weight    object               0          0.0

[64 rows x 4 columns]

FIRST FIVE RECORDS

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q8,s1q9,...,s3q223,s3q233,s3q243,s3q204,s3q20_o4,s3q214,s3q224,s3q234,s3q244,plot_weight
0,1,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,55,Large scale farmer as individual,Male,68,...,,,,,,,,,,1
1,2,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,55,Large scale farmer as individual,Male,68,...,,,,,,,,,,1
2,3,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,55,Large scale farmer as individual,Male,68,...,,,,,,,,,,1
3,4,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,55,Large scale farmer as individual,Male,68,...,,,,,,,,,,1
4,5,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,55,Large scale farmer as individual,Male,68,...,1,1,14000,,,,,,,1

NUMERICAL SUMMARY
No numerical columns detected.

=====================================================================================
DATASET: sas_2024_seasonB_production.json
=====================================================================================
Rows: 35,584 | Columns: 98
Missing cells: 0
Duplicate rows: 0
Memory usage: 175.26 MB

COLUMN INFORMATION

         Column Data Type  Missing Values  Missing (%)
0            id    object               0          0.0
1    Segment_ID    object               0          0.0
2          s1q1    object               0          0.0
3          s1q2    object               0          0.0
4          s1q3    object               0          0.0
..          ...       ...             ...          ...
93      s4q12_1    object               0          0.0
94        s4q14    object               0          0.0
95        s4q15    object               0          0.0
96        s5q12    object               0          0.0
97  plot_weight    object               0          0.0

[98 rows x 4 columns]

FIRST FIVE RECORDS

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q8,s1q9,...,s4q6,s4q8,s4q9,s4q10_1,s4q11_1,s4q12_1,s4q14,s4q15,s5q12,plot_weight
0,1,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,55,Large scale farmer as individual,Male,68,...,No,No,,,,,Yes,No,26/07/2024,1
1,2,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,55,Large scale farmer as individual,Male,68,...,No,No,,,,,Yes,No,26/07/2024,1
2,3,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,55,Large scale farmer as individual,Male,68,...,No,Yes,No,,,,Yes,Yes,26/07/2024,1
3,4,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,55,Large scale farmer as individual,Male,68,...,No,Yes,No,,,,Yes,Yes,26/07/2024,1
4,5,12001,Kigali,Gasabo,Large Scale Farmer/LSF,1,55,Large scale farmer as individual,Male,68,...,No,Yes,No,,,,Yes,Yes,26/07/2024,1

NUMERICAL SUMMARY
No numerical columns detected.

=====================================================================================
DATASET: sas_2024_seasonB_screening.json
=====================================================================================
Rows: 28,562 | Columns: 46
Missing cells: 0
Duplicate rows: 0
Memory usage: 67.57 MB

COLUMN INFORMATION

          Column Data Type  Missing Values  Missing (%)
0             id    object               0          0.0
1     Segment_ID    object               0          0.0
2           s1q1    object               0          0.0
3           s1q2    object               0          0.0
4           s1q3    object               0          0.0
5           s1q4    object               0          0.0
6         s1q5_2    object               0          0.0
7          s1q10    object               0          0.0
8          s1q13    object               0          0.0
9           s2q1    object               0          0.0
10          s2q2    object               0          0.0
11          s2q3    object               0          0.0
12          s2q4    object               0          0.0
13     s2q5_bloc    object               0          0.0
14          s2q5    object               0          0.0
15          s2q6    object               0          0.0
16          s2q7    object               0          0.0
17    s2q7_Other    object               0          0.0
18          s2q8    object               0          0.0
19        s2q9_1    object               0          0.0
20        s2q9_2    object               0          0.0
21        s2q9_3    object               0          0.0
22        s2q9_o    object               0          0.0
23         s2q10    object               0          0.0
24       s2q11_1    object               0          0.0
25       s2q11_2    object               0          0.0
26       s2q11_3    object               0          0.0
27       s2q11_4    object               0          0.0
28       s2q11_o    object               0          0.0
29         s2q12    object               0          0.0
30         s2q13    object               0          0.0
31         s2q14    object               0          0.0
32          s3q1    object               0          0.0
33        s3q1_o    object               0          0.0
34        s3q2_1    object               0          0.0
35        s3q2_2    object               0          0.0
36        s3q3_1    object               0          0.0
37        s3q3_2    object               0          0.0
38          s3q4    object               0          0.0
39          s3q5    object               0          0.0
40          s3q6    object               0          0.0
41          s3q7    object               0          0.0
42   plot_weight    object               0          0.0
43  CropCategory    object               0          0.0
44  Plot_size_ha    object               0          0.0
45     crop_area    object               0          0.0

FIRST FIVE RECORDS

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q5_2,s1q10,s1q13,s2q1,...,s3q3_1,s3q3_2,s3q4,s3q5,s3q6,s3q7,plot_weight,CropCategory,Plot_size_ha,crop_area
0,1,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,70,...,100,91%100%,,Yes,Yes,Between 16 -30/06,1,Fodder crops,0.4185936,0.4185936
1,2,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,5,...,100,91%100%,,Yes,Yes,Between 16 -30/06,1,Fodder crops,0.4061778,0.4061778
2,3,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,4,...,100,91%100%,,Yes,Yes,Between 16 -30/06,1,Fodder crops,0.7582782,0.7582782
3,4,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,2,...,100,91%100%,,Yes,Yes,Between 16 -30/06,1,Fodder crops,4.928037,4.928037
4,5,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,10,...,100,91%100%,,Yes,Yes,Between 16 -30/06,1,Fodder crops,3.00814,3.00814

NUMERICAL SUMMARY
No numerical columns detected.

=====================================================================================
DATASET: sas_2024_seasonC_agricultural_practice.json
=====================================================================================
Rows: 1,632 | Columns: 48
Missing cells: 0
Duplicate rows: 0
Memory usage: 3.98 MB

COLUMN INFORMATION

         Column Data Type  Missing Values  Missing (%)
0            id    object               0          0.0
1    Segment_ID    object               0          0.0
2          s2q1    object               0          0.0
3          s1q1    object               0          0.0
4          s1q2    object               0          0.0
5          s1q3    object               0          0.0
6          s1q4    object               0          0.0
7          s1q6    object               0          0.0
8          s1q7    object               0          0.0
9          s1q8    object               0          0.0
10         s1q9    object               0          0.0
11        s1q14    object               0          0.0
12        s1q17    object               0          0.0
13      s1q17_o    object               0          0.0
14         s2q2    object               0          0.0
15         s4q1    object               0          0.0
16         s4q2    object               0          0.0
17         s4q3    object               0          0.0
18         s4q4    object               0          0.0
19         s4q5    object               0          0.0
20         s4q6    object               0          0.0
21       s4q7_1    object               0          0.0
22       s4q7_2    object               0          0.0
23       s4q7_3    object               0          0.0
24       s4q7_4    object               0          0.0
25         s4q8    object               0          0.0
26         s4q9    object               0          0.0
27      s4q10_1    object               0          0.0
28      s4q10_3    object               0          0.0
29      s4q11_1    object               0          0.0
30      s4q11_3    object               0          0.0
31      s4q12_1    object               0          0.0
32      s4q12_2    object               0          0.0
33      s4q12_3    object               0          0.0
34      s4q12_4    object               0          0.0
35        s4q13    object               0          0.0
36        s4q14    object               0          0.0
37        s4q15    object               0          0.0
38        s4q16    object               0          0.0
39      s4q17_1    object               0          0.0
40      s4q17_2    object               0          0.0
41      s4q17_3    object               0          0.0
42      s4q18_1    object               0          0.0
43      s4q18_2    object               0          0.0
44      s4q18_3    object               0          0.0
45        s4q19    object               0          0.0
46  plot_weight    object               0          0.0
47      s2q2_ha    object               0          0.0

FIRST FIVE RECORDS

,id,Segment_ID,s2q1,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q8,...,s4q16,s4q17_1,s4q17_2,s4q17_3,s4q18_1,s4q18_2,s4q18_3,s4q19,plot_weight,s2q2_ha
0,1,111009,1,Kigali,Nyarugenge,Agricultural land on hillside,9,1,Small scale farmer as individual,Male,...,,,,,,,,,36.229675,0.0956858
1,2,111009,2,Kigali,Nyarugenge,Agricultural land on hillside,9,2,Small scale farmer as individual,Male,...,,,,,,,,,22.069442,0.1570799
2,3,111009,3,Kigali,Nyarugenge,Agricultural land on hillside,9,3,Small scale farmer as individual,Male,...,,,,,,,,,43.283657,0.0800918
3,4,111009,4,Kigali,Nyarugenge,Agricultural land on hillside,9,4,Small scale farmer as individual,Female,...,,,,,,,,,29.122975,0.1190355
4,5,111009,5,Kigali,Nyarugenge,Agricultural land on hillside,9,5,Small scale farmer as individual,Female,...,,,,,,,,,73.927968,0.093785

NUMERICAL SUMMARY
No numerical columns detected.

=====================================================================================
DATASET: sas_2024_seasonC_fertilizer_pesticide.json
=====================================================================================
Rows: 2,307 | Columns: 61
Missing cells: 0
Duplicate rows: 0
Memory usage: 7.02 MB

COLUMN INFORMATION

         Column Data Type  Missing Values  Missing (%)
0            id    object               0          0.0
1    Segment_ID    object               0          0.0
2          s1q1    object               0          0.0
3          s1q2    object               0          0.0
4          s1q3    object               0          0.0
..          ...       ...             ...          ...
56       s3q214    object               0          0.0
57       s3q224    object               0          0.0
58       s3q234    object               0          0.0
59       s3q244    object               0          0.0
60  plot_weight    object               0          0.0

[61 rows x 4 columns]

FIRST FIVE RECORDS

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q14,s2q1,...,s3q223,s3q233,s3q243,s3q204,s3q20_o4,s3q214,s3q224,s3q234,s3q244,plot_weight
0,1,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,1,Small scale farmer as individual,No,1,...,,,,,,,,,,36.229675
1,2,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,2,Small scale farmer as individual,No,2,...,,,,,,,,,,22.069442
2,3,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,3,Small scale farmer as individual,Yes,3,...,,,,,,,,,,43.283657
3,4,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,4,Small scale farmer as individual,Yes,4,...,,,,,,,,,,29.122975
4,5,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,5,Small scale farmer as individual,Yes,5,...,,,,,,,,,,73.927968

NUMERICAL SUMMARY
No numerical columns detected.

=====================================================================================
DATASET: sas_2024_seasonC_production.json
=====================================================================================
Rows: 1,949 | Columns: 97
Missing cells: 0
Duplicate rows: 0
Memory usage: 9.53 MB

COLUMN INFORMATION

         Column Data Type  Missing Values  Missing (%)
0            id    object               0          0.0
1    Segment_ID    object               0          0.0
2          s1q1    object               0          0.0
3          s1q2    object               0          0.0
4          s1q3    object               0          0.0
..          ...       ...             ...          ...
92      s4q12_1    object               0          0.0
93        s4q14    object               0          0.0
94        s4q15    object               0          0.0
95        s5q12    object               0          0.0
96  plot_weight    object               0          0.0

[97 rows x 4 columns]

FIRST FIVE RECORDS

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q8,s1q9,...,s4q6,s4q8,s4q9,s4q10_1,s4q11_1,s4q12_1,s4q14,s4q15,s5q12,plot_weight
0,1,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,1,Small scale farmer as individual,Male,64,...,No,No,,,,,No,,07/10/2024,36.229675
1,2,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,1,Small scale farmer as individual,Male,64,...,No,No,,,,,No,,07/10/2024,36.229675
2,3,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,2,Small scale farmer as individual,Male,79,...,No,No,,,,,No,,03/10/2024,22.069442
3,4,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,2,Small scale farmer as individual,Male,79,...,No,No,,,,,No,,03/10/2024,22.069442
4,5,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,3,Small scale farmer as individual,Male,89,...,No,No,,,,,No,,04/10/2024,43.283657

NUMERICAL SUMMARY
No numerical columns detected.

=====================================================================================
DATASET: sas_2024_seasonC_screening.json
=====================================================================================
Rows: 8,195 | Columns: 42
Missing cells: 0
Duplicate rows: 0
Memory usage: 17.38 MB

COLUMN INFORMATION

          Column Data Type  Missing Values  Missing (%)
0             id    object               0          0.0
1     Segment_ID    object               0          0.0
2           s1q1    object               0          0.0
3           s1q2    object               0          0.0
4           s1q3    object               0          0.0
5           s1q4    object               0          0.0
6         s1q5_2    object               0          0.0
7          s1q13    object               0          0.0
8           s2q1    object               0          0.0
9           s2q3    object               0          0.0
10          s2q4    object               0          0.0
11          s2q5    object               0          0.0
12          s2q6    object               0          0.0
13          s2q7    object               0          0.0
14    s2q7_Other    object               0          0.0
15          s2q8    object               0          0.0
16        s2q9_1    object               0          0.0
17        s2q9_2    object               0          0.0
18        s2q9_3    object               0          0.0
19        s2q9_o    object               0          0.0
20         s2q10    object               0          0.0
21       s2q11_1    object               0          0.0
22       s2q11_2    object               0          0.0
23       s2q11_3    object               0          0.0
24       s2q11_4    object               0          0.0
25       s2q11_o    object               0          0.0
26         s2q12    object               0          0.0
27         s2q13    object               0          0.0
28         s2q14    object               0          0.0
29          s3q1    object               0          0.0
30        s3q1_o    object               0          0.0
31        s3q2_1    object               0          0.0
32        s3q2_2    object               0          0.0
33        s3q3_1    object               0          0.0
34        s3q3_2    object               0          0.0
35          s3q5    object               0          0.0
36          s3q6    object               0          0.0
37          s3q7    object               0          0.0
38   plot_weight    object               0          0.0
39  CropCategory    object               0          0.0
40  Plot_size_ha    object               0          0.0
41     Crop_Area    object               0          0.0

FIRST FIVE RECORDS

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q5_2,s1q13,s2q1,s2q3,...,s3q2_2,s3q3_1,s3q3_2,s3q5,s3q6,s3q7,plot_weight,CropCategory,Plot_size_ha,Crop_Area
0,1,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,1,9,1,1,...,61%-70%,60,51%-60%,Yes,Yes,Between 16 -30/09,36.229675,Bush bean,0.0956858,0.0669801
1,2,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,1,9,1,1,...,31%-40%,40,31%-40%,Yes,Yes,After 30/09,36.229675,Soybean,0.0956858,0.03349
2,3,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,1,9,1,1,...,10% -20%,15,10% 20%,No,No,Other season,36.229675,Maize,0.0956858,0.0143529
3,4,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,2,9,2,1,...,61%-70%,45,41%-50%,Yes,Yes,Between 16 -30/09,22.069442,Bush bean,0.1570799,0.102102
4,5,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,2,9,2,1,...,10% -20%,10,10% 20%,No,No,Other season,22.069442,Maize,0.1570799,0.015708

NUMERICAL SUMMARY
No numerical columns detected.

=====================================================================================
OVERALL DATA UNDERSTANDING SUMMARY
=====================================================================================

,Dataset,Rows,Columns,Missing Cells,Duplicate Rows,Memory (MB)
0,sas_2024_seasonA_agricultural_practice.json,17506,59,0,0,51.17
1,sas_2024_seasonA_fertilizer_pesticide.json,22105,64,0,0,70.24
2,sas_2024_seasonA_production.json,39330,96,0,0,189.79
3,sas_2024_seasonA_screening.json,54382,46,0,0,129.63
4,sas_2024_seasonB_agricultural_practice.json,17261,53,0,0,45.62
5,sas_2024_seasonB_fertilizer_pesticide.json,19965,64,0,0,63.24
6,sas_2024_seasonB_production.json,35584,98,0,0,175.26
7,sas_2024_seasonB_screening.json,28562,46,0,0,67.57
8,sas_2024_seasonC_agricultural_practice.json,1632,48,0,0,3.98
9,sas_2024_seasonC_fertilizer_pesticide.json,2307,61,0,0,7.02
10,sas_2024_seasonC_production.json,1949,97,0,0,9.53
11,sas_2024_seasonC_screening.json,8195,42,0,0,17.38

Datasets loaded: 12/12
Total rows: 248,778
Total columns: 774
Total missing cells: 0
Total duplicate rows: 0
Combined DataFrame memory: 830.43 MB

All 12 datasets were loaded successfully.

Data Understanding completed. No downloads were performed.

In [6]:

# ============================================================
# 5. DATA CLEANING
# 5.1 INITIAL DATA QUALITY ASSESSMENT
# ============================================================

import numpy as np
import pandas as pd
from IPython.display import display

if "datasets" not in globals() or not datasets:
    raise RuntimeError(
        "No datasets are loaded. Run the Load Dataset section first."
    )

# Preserve the originally loaded datasets
raw_datasets = {
    name: df.copy(deep=True)
    for name, df in datasets.items()
}

quality_report = []

for name, df in raw_datasets.items():

    # Count missing values and blank strings separately
    missing_values = int(df.isna().sum().sum())

    blank_cells = int(
        df.select_dtypes(include=["object", "string"])
          .apply(
              lambda column: column.astype("string")
              .str.strip()
              .eq("")
              .fillna(False)
          )
          .sum()
          .sum()
    )

    quality_report.append({
        "Dataset": name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Missing Values": missing_values,
        "Blank Cells": blank_cells,
        "Duplicate Rows": int(df.duplicated().sum()),
        "Object Columns": int(
            df.dtypes.astype(str).eq("object").sum()
        ),
        "Memory (MB)": round(
            df.memory_usage(deep=True).sum() / (1024 ** 2), 2
        )
    })

quality_report_df = pd.DataFrame(quality_report)

print("INITIAL DATA QUALITY REPORT")
display(quality_report_df)

print("\nTotal datasets inspected:", len(raw_datasets))
print("Original datasets preserved in raw_datasets.")

INITIAL DATA QUALITY REPORT

,Dataset,Rows,Columns,Missing Values,Blank Cells,Duplicate Rows,Object Columns,Memory (MB)
0,sas_2024_seasonA_agricultural_practice,17506,59,0,624768,0,59,51.17
1,sas_2024_seasonA_fertilizer_pesticide,22105,64,0,729532,0,64,70.24
2,sas_2024_seasonA_production,39330,96,0,1007574,0,96,189.79
3,sas_2024_seasonA_screening,54382,46,0,737430,0,46,129.63
4,sas_2024_seasonB_agricultural_practice,17261,53,0,511665,0,53,45.62
5,sas_2024_seasonB_fertilizer_pesticide,19965,64,0,698483,0,64,63.24
6,sas_2024_seasonB_production,35584,98,0,866751,0,98,175.26
7,sas_2024_seasonB_screening,28562,46,0,443594,0,46,67.57
8,sas_2024_seasonC_agricultural_practice,1632,48,0,35653,0,48,3.98
9,sas_2024_seasonC_fertilizer_pesticide,2307,61,0,66591,0,61,7.02
10,sas_2024_seasonC_production,1949,97,0,38662,0,97,9.53
11,sas_2024_seasonC_screening,8195,42,0,139618,0,42,17.38

Total datasets inspected: 12
Original datasets preserved in raw_datasets.

In [7]:

# ============================================================
# DATA CLEANING — BLANK RESPONSE ANALYSIS
# ============================================================

import pandas as pd
import numpy as np
from IPython.display import display

blank_summary = []
blank_columns = {}

for name, df in raw_datasets.items():

    # Count empty strings and whitespace-only strings
    text_df = df.select_dtypes(
        include=["object", "string"]
    )

    blank_mask = text_df.apply(
        lambda col: col.astype("string")
        .str.strip()
        .eq("")
        .fillna(False)
    )

    total_cells = df.shape[0] * df.shape[1]
    blank_count = int(blank_mask.sum().sum())

    blank_summary.append({
        "Dataset": name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Blank Cells": blank_count,
        "Total Cells": total_cells,
        "Blank Percentage": round(
            blank_count / total_cells * 100, 2
        ) if total_cells else 0
    })

    # Identify columns with the most blank responses
    column_blanks = blank_mask.sum().sort_values(
        ascending=False
    )

    column_blanks = column_blanks[column_blanks > 0]

    blank_columns[name] = column_blanks

print("BLANK RESPONSE SUMMARY")
display(
    pd.DataFrame(blank_summary).sort_values(
        "Blank Percentage", ascending=False
    )
)

# Inspect the 10 most blank columns in each dataset
for name, counts in blank_columns.items():

    print(f"\n{name} — TOP 10 COLUMNS WITH BLANK RESPONSES")

    if counts.empty:
        print("No blank responses detected.")
    else:
        display(
            counts.head(10).rename("Blank Cells").to_frame()
        )

BLANK RESPONSE SUMMARY

,Dataset,Rows,Columns,Blank Cells,Total Cells,Blank Percentage
0,sas_2024_seasonA_agricultural_practice,17506,59,624768,1032854,60.49
4,sas_2024_seasonB_agricultural_practice,17261,53,511665,914833,55.93
5,sas_2024_seasonB_fertilizer_pesticide,19965,64,698483,1277760,54.66
1,sas_2024_seasonA_fertilizer_pesticide,22105,64,729532,1414720,51.57
9,sas_2024_seasonC_fertilizer_pesticide,2307,61,66591,140727,47.32
8,sas_2024_seasonC_agricultural_practice,1632,48,35653,78336,45.51
11,sas_2024_seasonC_screening,8195,42,139618,344190,40.56
7,sas_2024_seasonB_screening,28562,46,443594,1313852,33.76
3,sas_2024_seasonA_screening,54382,46,737430,2501572,29.48
2,sas_2024_seasonA_production,39330,96,1007574,3775680,26.69
6,sas_2024_seasonB_production,35584,98,866751,3487232,24.85
10,sas_2024_seasonC_production,1949,97,38662,189053,20.45

sas_2024_seasonA_agricultural_practice — TOP 10 COLUMNS WITH BLANK RESPONSES

           Blank Cells
s4q10_2_4        17505
s4q10_2_3        17505
s4q10_2_2        17505
s4q12_2_2        17505
s4q12_2_3        17505
s4q17_3          17504
s4q18_3          17502
s4q12_2_1        17499
s4q12_4          17499
s4q12_3          17499

sas_2024_seasonA_fertilizer_pesticide — TOP 10 COLUMNS WITH BLANK RESPONSES

          Blank Cells
s3q2_3          22081
s3q20_o1        22039
s3q20_o4        22024
s3q10_o         21993
s3q20_o2        21989
s3q20_o3        21966
s3q244          21817
s3q224          21817
s3q214          21817
s3q234          21817

sas_2024_seasonA_production — TOP 10 COLUMNS WITH BLANK RESPONSES

         Blank Cells
s2q10_o        39252
s2q4_o         39236
s4q11_1        39116
s4q10_1        39116
s4q12_1        39116
s3q17          39057
s4q9           38933
s2q37          37732
s2q24_c        37524
s4q15          36537

sas_2024_seasonA_screening — TOP 10 COLUMNS WITH BLANK RESPONSES

            Blank Cells
s2q9_o            54356
s2q7_Other        54302
s3q1_o            54129
s2q11_o           54042
s2q11_4           54041
s2q9_3            52859
s2q11_3           52622
s2q7              49986
s2q2              48291
s2q11_2           47467

sas_2024_seasonB_agricultural_practice — TOP 10 COLUMNS WITH BLANK RESPONSES

           Blank Cells
s4q10_3          17261
s4q18_4          17259
s4q17_3          17259
s4q11_2_4        17257
s4q12_4          17257
s4q12_3          17257
s4q11_2_5        17257
s4q11_2_3        17233
s4q18_3          17233
s4q17_2          17225

sas_2024_seasonB_fertilizer_pesticide — TOP 10 COLUMNS WITH BLANK RESPONSES

          Blank Cells
s3q2_3          19951
s3q20_o1        19934
s3q20_o4        19926
s3q20_o2        19900
s3q20_o3        19890
s3q10_o         19876
s3q234          19759
s3q214          19759
s3q224          19759
s3q244          19759

sas_2024_seasonB_production — TOP 10 COLUMNS WITH BLANK RESPONSES

         Blank Cells
s2q10_o        35522
s2q4_o         35496
s4q12_1        35398
s4q10_1        35394
s4q11_1        35394
s3q17          35321
s4q9           35233
s1q17_o        35170
s2q37          34612
s2q24_c        33295

sas_2024_seasonB_screening — TOP 10 COLUMNS WITH BLANK RESPONSES

            Blank Cells
s2q9_o            28557
s2q7_Other        28483
s2q11_o           28447
s2q11_4           28439
s3q1_o            28311
s2q9_3            27936
s2q11_3           27895
s2q11_2           25735
s2q7              24305
s2q2              23453

sas_2024_seasonC_agricultural_practice — TOP 10 COLUMNS WITH BLANK RESPONSES

         Blank Cells
s4q11_3         1632
s4q10_3         1632
s4q12_2         1631
s4q12_3         1631
s4q10_1         1631
s4q11_1         1631
s4q12_4         1631
s4q12_1         1631
s4q17_3         1631
s4q9            1628

sas_2024_seasonC_fertilizer_pesticide — TOP 10 COLUMNS WITH BLANK RESPONSES

              Blank Cells
s3q2_o               2307
q_3_10_other         2305
s3q2_3               2304
s3q20_o1             2288
s3q20_o4             2274
s3q20_o2             2264
s3q10_o              2257
s3q17                2254
s3q20_o3             2245
s3q224               2191

sas_2024_seasonC_production — TOP 10 COLUMNS WITH BLANK RESPONSES

         Blank Cells
s4q10_1         1948
s4q11_1         1948
s4q12_1         1948
s2q4_o          1945
s4q9            1944
s1q17_o         1942
s2q10_o         1938
s2q37           1930
s3q17           1917
s2q24_c         1803

sas_2024_seasonC_screening — TOP 10 COLUMNS WITH BLANK RESPONSES

            Blank Cells
s2q11_4            8189
s2q11_o            8183
s3q1_o             8172
s2q9_o             8169
s2q7_Other         8162
s2q11_3            8137
s2q9_3             8053
s2q11_2            7856
s2q7               7069
s2q9_2             6616

In [8]:

# ============================================================
# 5.6 CLASSIFY COLUMNS BY BLANK PERCENTAGE
# ============================================================

column_quality_reports = []

for name, df in raw_datasets.items():

    text_df = df.select_dtypes(include=["object", "string"])

    blank_mask = text_df.apply(
        lambda col: col.astype("string")
        .str.strip()
        .eq("")
        .fillna(False)
    )

    for column in df.columns:

        blank_count = (
            int(blank_mask[column].sum())
            if column in blank_mask.columns
            else 0
        )

        total_rows = len(df)

        blank_pct = (
            blank_count / total_rows * 100
            if total_rows else 0
        )

        if blank_pct >= 95:
            status = "Nearly empty"
        elif blank_pct > 0:
            status = "Partially populated"
        else:
            status = "Complete"

        column_quality_reports.append({
            "Dataset": name,
            "Column": column,
            "Blank Count": blank_count,
            "Blank Percentage": round(blank_pct, 2),
            "Status": status
        })

column_quality_df = pd.DataFrame(column_quality_reports)

print("COLUMN QUALITY CLASSIFICATION")
display(
    column_quality_df.sort_values(
        ["Dataset", "Blank Percentage"],
        ascending=[True, False]
    ).groupby("Dataset").head(10).reset_index(drop=True)
)

print("\nCOLUMN COUNTS BY STATUS")
display(
    column_quality_df.groupby(
        ["Dataset", "Status"]
    ).size().unstack(fill_value=0)
)

COLUMN QUALITY CLASSIFICATION

,Dataset,Column,Blank Count,Blank Percentage,Status
0,sas_2024_seasonA_agricultural_practice,s4q10_2_2,17505,99.99,Nearly empty
1,sas_2024_seasonA_agricultural_practice,s4q10_2_3,17505,99.99,Nearly empty
2,sas_2024_seasonA_agricultural_practice,s4q10_2_4,17505,99.99,Nearly empty
3,sas_2024_seasonA_agricultural_practice,s4q12_2_2,17505,99.99,Nearly empty
4,sas_2024_seasonA_agricultural_practice,s4q12_2_3,17505,99.99,Nearly empty
...,...,...,...,...,...
115,sas_2024_seasonC_screening,s2q11_3,8137,99.29,Nearly empty
116,sas_2024_seasonC_screening,s2q9_3,8053,98.27,Nearly empty
117,sas_2024_seasonC_screening,s2q11_2,7856,95.86,Nearly empty
118,sas_2024_seasonC_screening,s2q7,7069,86.26,Partially populated
119,sas_2024_seasonC_screening,s2q9_2,6616,80.73,Partially populated

COLUMN COUNTS BY STATUS

Status,Complete,Nearly empty,Partially populated
Dataset,,,
sas_2024_seasonA_agricultural_practice,19,33,7
sas_2024_seasonA_fertilizer_pesticide,19,17,28
sas_2024_seasonA_production,30,9,57
sas_2024_seasonA_screening,2,7,37
sas_2024_seasonB_agricultural_practice,13,27,13
sas_2024_seasonB_fertilizer_pesticide,14,17,33
sas_2024_seasonB_production,17,9,72
sas_2024_seasonB_screening,16,7,23
sas_2024_seasonC_agricultural_practice,19,16,13
sas_2024_seasonC_fertilizer_pesticide,17,9,35
sas_2024_seasonC_production,62,9,26
sas_2024_seasonC_screening,13,8,21

In [10]:

# ============================================================
# FIX: INITIALIZE FINAL CLEANED DATASETS
# ============================================================

import pandas as pd

if "cleaned_datasets" in globals() and cleaned_datasets:
    source_datasets = cleaned_datasets
elif "raw_datasets" in globals() and raw_datasets:
    source_datasets = raw_datasets
elif "datasets" in globals() and datasets:
    source_datasets = datasets
else:
    raise RuntimeError(
        "No datasets are loaded. Run the Load Dataset cell first."
    )

final_cleaned_datasets = {}

for name, original_df in source_datasets.items():
    df = original_df.copy(deep=True)

    # Standardize empty strings as missing values
    for column in df.select_dtypes(
        include=["object", "string"]
    ).columns:
        df[column] = df[column].replace(
            r"^\s*$", pd.NA, regex=True
        )

    final_cleaned_datasets[name] = df

print("SUCCESS: final_cleaned_datasets is ready.")
print("Datasets available:", len(final_cleaned_datasets))

display(pd.DataFrame([
    {
        "Dataset": name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Missing Cells": int(df.isna().sum().sum())
    }
    for name, df in final_cleaned_datasets.items()
]))

SUCCESS: final_cleaned_datasets is ready.
Datasets available: 12

                                   Dataset   Rows  Columns  Missing Cells
0   sas_2024_seasonA_agricultural_practice  17506       59         624768
1    sas_2024_seasonA_fertilizer_pesticide  22105       64         729532
2              sas_2024_seasonA_production  39330       96        1007574
3               sas_2024_seasonA_screening  54382       46         737430
4   sas_2024_seasonB_agricultural_practice  17261       53         511665
5    sas_2024_seasonB_fertilizer_pesticide  19965       64         698483
6              sas_2024_seasonB_production  35584       98         866751
7               sas_2024_seasonB_screening  28562       46         443594
8   sas_2024_seasonC_agricultural_practice   1632       48          35653
9    sas_2024_seasonC_fertilizer_pesticide   2307       61          66591
10             sas_2024_seasonC_production   1949       97          38662
11              sas_2024_seasonC_screening   8195       42         139618

In [11]:

# 6.1 — Inspect Screening Datasets

import pandas as pd
from IPython.display import display

screening_datasets = {
    name: df.copy()
    for name, df in final_cleaned_datasets.items()
    if "screening" in name.lower()
}

print(f"Screening datasets found: {len(screening_datasets)}")

for name, df in screening_datasets.items():
    print("\n" + "=" * 80)
    print(f"DATASET: {name}")
    print(f"Shape: {df.shape}")
    print("Available columns:")
    print(df.columns.tolist())

    display(df.head(3))

Screening datasets found: 3

================================================================================
DATASET: sas_2024_seasonA_screening
Shape: (54382, 46)
Available columns:
['id', 'Segment_ID', 's1q1', 's1q2', 's1q3', 's1q4', 's1q5_2', 's1q10', 's1q13', 's2q1', 's2q2', 's2q3', 's2q4', 's2q5_bloc', 's2q5', 's2q6', 's2q7', 's2q7_Other', 's2q8', 's2q9_1', 's2q9_2', 's2q9_3', 's2q9_o', 's2q10', 's2q11_1', 's2q11_2', 's2q11_3', 's2q11_4', 's2q11_o', 's2q12', 's2q13', 's2q14', 's3q1', 's3q2_1', 's3q2_2', 's3q3_1', 's3q3_2', 's3q4', 's3q5', 's3q6', 's3q7', 'CropCategory', 's3q1_o', 'plot_weight', 'Plot_size_ha', 'crop_area']

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q5_2,s1q10,s1q13,s2q1,...,s3q3_2,s3q4,s3q5,s3q6,s3q7,CropCategory,s3q1_o,plot_weight,Plot_size_ha,crop_area
0,1,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,1,...,91%100%,<NA>,Yes,Yes,Before 01/12,Fodder crops,<NA>,1,6.933567,6.933567
1,2,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,2,...,91%100%,<NA>,Yes,Yes,Between 01-15/01,Fodder crops,<NA>,1,33.87405,32.18035
2,3,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,2,...,91%100%,<NA>,Yes,Yes,Between 01-28/02,Fodder crops,<NA>,1,33.87405,33.87405

================================================================================
DATASET: sas_2024_seasonB_screening
Shape: (28562, 46)
Available columns:
['id', 'Segment_ID', 's1q1', 's1q2', 's1q3', 's1q4', 's1q5_2', 's1q10', 's1q13', 's2q1', 's2q2', 's2q3', 's2q4', 's2q5_bloc', 's2q5', 's2q6', 's2q7', 's2q7_Other', 's2q8', 's2q9_1', 's2q9_2', 's2q9_3', 's2q9_o', 's2q10', 's2q11_1', 's2q11_2', 's2q11_3', 's2q11_4', 's2q11_o', 's2q12', 's2q13', 's2q14', 's3q1', 's3q1_o', 's3q2_1', 's3q2_2', 's3q3_1', 's3q3_2', 's3q4', 's3q5', 's3q6', 's3q7', 'plot_weight', 'CropCategory', 'Plot_size_ha', 'crop_area']

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q5_2,s1q10,s1q13,s2q1,...,s3q3_1,s3q3_2,s3q4,s3q5,s3q6,s3q7,plot_weight,CropCategory,Plot_size_ha,crop_area
0,1,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,70,...,100,91%100%,<NA>,Yes,Yes,Between 16 -30/06,1,Fodder crops,0.4185936,0.4185936
1,2,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,5,...,100,91%100%,<NA>,Yes,Yes,Between 16 -30/06,1,Fodder crops,0.4061778,0.4061778
2,3,12001,Kigali,Gasabo,Large Scale Farmer/LSF,99,1,Individual large farmer,99,4,...,100,91%100%,<NA>,Yes,Yes,Between 16 -30/06,1,Fodder crops,0.7582782,0.7582782

================================================================================
DATASET: sas_2024_seasonC_screening
Shape: (8195, 42)
Available columns:
['id', 'Segment_ID', 's1q1', 's1q2', 's1q3', 's1q4', 's1q5_2', 's1q13', 's2q1', 's2q3', 's2q4', 's2q5', 's2q6', 's2q7', 's2q7_Other', 's2q8', 's2q9_1', 's2q9_2', 's2q9_3', 's2q9_o', 's2q10', 's2q11_1', 's2q11_2', 's2q11_3', 's2q11_4', 's2q11_o', 's2q12', 's2q13', 's2q14', 's3q1', 's3q1_o', 's3q2_1', 's3q2_2', 's3q3_1', 's3q3_2', 's3q5', 's3q6', 's3q7', 'plot_weight', 'CropCategory', 'Plot_size_ha', 'Crop_Area']

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q5_2,s1q13,s2q1,s2q3,...,s3q2_2,s3q3_1,s3q3_2,s3q5,s3q6,s3q7,plot_weight,CropCategory,Plot_size_ha,Crop_Area
0,1,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,1,9,1,1,...,61%-70%,60,51%-60%,Yes,Yes,Between 16 -30/09,36.229675,Bush bean,0.0956858,0.0669801
1,2,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,1,9,1,1,...,31%-40%,40,31%-40%,Yes,Yes,After 30/09,36.229675,Soybean,0.0956858,0.03349
2,3,111009,Kigali,Nyarugenge,Agricultural land on hillside,9,1,9,1,1,...,10% -20%,15,10% 20%,No,No,Other season,36.229675,Maize,0.0956858,0.0143529

In [12]:

# 6.3 — Combine Seasons A, B, and C

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

screening_frames = []

for name, df in screening_datasets.items():
    temp = df.copy()

    # Identify the season from the dataset name
    season = name.split("_")[2].upper()
    temp["Season"] = season

    # Standardize column names that differ between seasons
    temp.columns = [
        "crop_area" if col.lower() == "crop_area" else col
        for col in temp.columns
    ]

    screening_frames.append(temp)

screening_all = pd.concat(
    screening_frames,
    ignore_index=True,
    sort=False
)

# Standardize text fields and blank responses
for col in screening_all.select_dtypes(include=["object", "string"]).columns:
    screening_all[col] = screening_all[col].replace(
        r"^\s*$", pd.NA, regex=True
    )

# Convert area and weight fields to numeric safely
for col in ["Plot_size_ha", "crop_area", "plot_weight"]:
    if col in screening_all.columns:
        screening_all[col] = pd.to_numeric(
            screening_all[col], errors="coerce"
        )

print("Combined screening dataset:", screening_all.shape)
print("\nRecords by season:")
display(screening_all["Season"].value_counts().sort_index().rename("Records").to_frame())

print("\nKey variable summary:")
display(
    screening_all[
        ["CropCategory", "Plot_size_ha", "crop_area", "plot_weight"]
    ].describe(include="all").T
)

Combined screening dataset: (91139, 47)

Records by season:

         Records
Season
SEASONA    54382
SEASONB    28562
SEASONC     8195

Key variable summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
CropCategory,74335,22,Maize,11036,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Plot_size_ha,91138.0,NaN,NaN,NaN,8.228713,62.197894,0.001043,0.048757,0.104034,0.261653,1651.444
crop_area,73895.0,NaN,NaN,NaN,9.391295,65.385919,0.0,0.021082,0.050178,0.13112,1637.272
plot_weight,91138.0,NaN,NaN,NaN,875.479661,1243.493364,0.0,200.7139,490.2313,1076.71025,53450.5

In [20]:

import pandas as pd
import numpy as np

# Inspect selected variables that need further investigation.
variables_to_check = [
    "s2q13_2", "s2q14", "s2q15",
    "s2q16_2", "s2q17", "s2q46",
    "s2q47", "s2q48", "s2q49", "s2q50"
]

for dataset_name, df in final_cleaned_datasets.items():
    if "production" not in dataset_name.lower():
        continue

    print(f"\n{'=' * 90}")
    print(f"DATASET: {dataset_name}")
    print(f"{'=' * 90}")

    for variable in variables_to_check:
        if variable not in df.columns:
            continue

        values = pd.to_numeric(df[variable], errors="coerce")
        valid = values.dropna()

        if valid.empty:
            continue

        # Investigate negative values.
        negative_rows = df.loc[values < 0]

        if not negative_rows.empty:
            print(f"\n{variable}: {len(negative_rows)} negative records")
            display(negative_rows.head(10))

        # Investigate unusually large values using the IQR rule.
        q1 = valid.quantile(0.25)
        q3 = valid.quantile(0.75)
        iqr = q3 - q1
        upper_bound = q3 + 1.5 * iqr

        extreme_rows = df.loc[values > upper_bound]

        if not extreme_rows.empty:
            print(
                f"\n{variable}: {len(extreme_rows)} values "
                f"above the IQR investigation threshold ({upper_bound:.2f})"
            )

            columns_to_show = [
                col for col in [
                    "s1q1", "s1q2", "s2q4",
                    "CropCategory", variable, "plot_weight"
                ]
                if col in df.columns
            ]

            display(
                extreme_rows[columns_to_show]
                .sort_values(variable, ascending=False)
                .head(10)
            )

==========================================================================================
DATASET: sas_2024_seasonA_production
==========================================================================================

s2q13_2: 3880 values above the IQR investigation threshold (72.00)

         s1q1       s1q2     s2q4 CropCategory s2q13_2 plot_weight
39223    East   Bugesera  Cassava      Cassava     995    807.7324
10576   South    Ruhango  Cassava      Cassava     995    324.8902
7632    South       Huye  Cassava      Cassava     995    140.2103
37118    East      Ngoma  Cassava      Cassava     995    370.2881
33307    East    Kayonza  Cassava      Cassava     995    327.4109
28638    East  Rwamagana  Cassava      Cassava     994    305.0654
18974    West     Rusizi  Cassava      Cassava     993    419.2798
37667    East   Bugesera  Cassava      Cassava     993    354.7711
33239    East    Kayonza  Cassava      Cassava     993    164.1734
2304   Kigali     Gasabo  Cassava      Cassava     990    61.16062

s2q14: 2566 values above the IQR investigation threshold (7.50)

        s1q1        s1q2          s2q4  CropCategory s2q14 plot_weight
17006   West     Nyabihu  Irish potato  Irish potato  99.2    352.5129
20564   West  Nyamasheke       Cassava       Cassava   985     251.906
12812  South     Kamonyi       Cassava       Cassava   970    481.1386
27683   East   Rwamagana       Cassava       Cassava   963    118.2037
21816  North     Rulindo       Cassava       Cassava    95     947.527
8922   South   Nyamagabe       Cassava       Cassava    95    645.0734
31334   East     Gatsibo     Bush bean     Bush bean    94    71.36964
12693  South     Kamonyi       Cassava       Cassava   930    620.7671
24016  North     Musanze  Irish potato  Irish potato    92    616.3477
15720   West     Rutsiro  Irish potato  Irish potato    91    526.9747

s2q15: 932 values above the IQR investigation threshold (24000.00)

        s1q1     s1q2          s2q4  CropCategory   s2q15 plot_weight
15995   West   Rubavu  Irish potato  Irish potato   98000    620.8582
15994   West   Rubavu  Irish potato  Irish potato   98000    374.6743
24079  North  Musanze  Irish potato  Irish potato  975000    117.0707
16833   West  Nyabihu  Irish potato  Irish potato   97500    138.6589
16059   West   Rubavu  Irish potato  Irish potato   96000    1541.281
31460   East  Gatsibo  Irish potato  Irish potato   96000    217.6828
16468   West   Rubavu  Irish potato  Irish potato   96000    474.1303
17196   West  Nyabihu  Irish potato  Irish potato   96000    684.6703
22969  North  Gakenke  Irish potato  Irish potato   96000    499.9068
24411  North  Musanze  Irish potato  Irish potato   96000    486.5683

s2q16_2: 1134 values above the IQR investigation threshold (11.00)

       s1q1       s1q2          s2q4  CropCategory s2q16_2 plot_weight
915    East    Gatsibo    Paddy rice    Paddy rice     990           1
135   South     Nyanza         Maize         Maize   978.5           1
1294   East   Bugesera         Maize         Maize     975           1
229   South  Nyamagabe  Irish potato  Irish potato  9656.9           1
1298   East   Bugesera    Paddy rice    Paddy rice     960           1
1137   East    Kayonza         Maize         Maize      96           1
1070   East    Kayonza    Paddy rice    Paddy rice   949.8           1
1027   East    Kayonza         Maize         Maize     936           1
644    East  Rwamagana     Bush bean     Bush bean      93           1
225   South       Huye         Maize         Maize   928.6           1

s2q17: 1137 values above the IQR investigation threshold (8.80)

       s1q1       s1q2        s2q4 CropCategory  s2q17 plot_weight
915    East    Gatsibo  Paddy rice   Paddy rice    990           1
135   South     Nyanza       Maize        Maize  978.5           1
1294   East   Bugesera       Maize        Maize    975           1
1298   East   Bugesera  Paddy rice   Paddy rice    960           1
1137   East    Kayonza       Maize        Maize     96           1
1070   East    Kayonza  Paddy rice   Paddy rice  949.8           1
1027   East    Kayonza       Maize        Maize    936           1
644    East  Rwamagana   Bush bean    Bush bean     93           1
225   South       Huye       Maize        Maize  928.6           1
173   South  Nyaruguru       Maize        Maize    924           1

s2q46: 1019 values above the IQR investigation threshold (0.00)

         s1q1       s1q2          s2q4  CropCategory s2q46 plot_weight
38     Kigali     Gasabo    Paddy rice    Paddy rice    94           1
1039     East    Kayonza    Paddy rice    Paddy rice  9192           1
1217     East      Ngoma    Paddy rice    Paddy rice   900           1
1270     East      Ngoma        Pepper    Vegetables    90           1
16143    West     Rubavu        Garlic    Vegetables    90    256.8427
22270   North    Rulindo  Irish potato  Irish potato     9    913.0629
1162     East     Kirehe    Paddy rice    Paddy rice  8420           1
919      East    Gatsibo         Maize         Maize   816           1
804      East  Nyagatare  Irish potato  Irish potato   800           1
801      East  Nyagatare  Irish potato  Irish potato   800           1

s2q47: 142 negative records

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q8,s1q9,...,s4q6,s4q8,s4q9,s4q10_1,s4q11_1,s4q12_1,s4q14,s4q15,s5q12,plot_weight
148,149,22004,South,Gisagara,Large Scale Farmer/LSF,11,1,Large scale farmer as Coperative/Company/Asso...,<NA>,<NA>,...,Yes,No,<NA>,<NA>,<NA>,<NA>,No,<NA>,19/02/2024,1
151,152,22010,South,Gisagara,Large Scale Farmer/LSF,10,2,Large scale farmer as Coperative/Company/Asso...,<NA>,<NA>,...,Yes,No,<NA>,<NA>,<NA>,<NA>,Yes,Yes,21/02/2024,1
739,740,52022,East,Nyagatare,Large Scale Farmer/LSF,22,22,Large scale farmer as Coperative/Company/Asso...,<NA>,<NA>,...,Yes,Yes,Yes,No,Yes,No,Yes,No,05/03/2024,1
742,743,52022,East,Nyagatare,Large Scale Farmer/LSF,22,22,Large scale farmer as Coperative/Company/Asso...,<NA>,<NA>,...,Yes,Yes,No,<NA>,<NA>,<NA>,Yes,Yes,05/03/2024,1
5421,5422,221009,South,Gisagara,Agricultural land on hillside,9,14,Small scale farmer as individual,Male,42,...,No,No,<NA>,<NA>,<NA>,<NA>,Yes,No,26/01/2024,251.4092
5423,5424,221009,South,Gisagara,Agricultural land on hillside,9,14,Small scale farmer as individual,Male,42,...,No,No,<NA>,<NA>,<NA>,<NA>,Yes,No,26/01/2024,251.4092
5437,5438,221009,South,Gisagara,Agricultural land on hillside,9,14,Small scale farmer as individual,Male,42,...,No,No,<NA>,<NA>,<NA>,<NA>,No,<NA>,26/01/2024,304.0784
5438,5439,221009,South,Gisagara,Agricultural land on hillside,9,14,Small scale farmer as individual,Male,42,...,No,No,<NA>,<NA>,<NA>,<NA>,No,<NA>,26/01/2024,304.0784
5449,5450,221009,South,Gisagara,Agricultural land on hillside,9,14,Small scale farmer as individual,Male,42,...,No,No,<NA>,<NA>,<NA>,<NA>,Yes,No,26/01/2024,231.2164
5450,5451,221009,South,Gisagara,Agricultural land on hillside,9,14,Small scale farmer as individual,Male,42,...,No,No,<NA>,<NA>,<NA>,<NA>,Yes,No,26/01/2024,231.2164

s2q47: 327 values above the IQR investigation threshold (0.00)

         s1q1        s1q2             s2q4     CropCategory s2q47 plot_weight
17424    West   Ngororero  Banana for beer  Banana for beer    96    1241.674
22518   North     Gakenke  Banana for beer  Banana for beer    95    393.3084
4715    South      Nyanza   Dessert banana   Dessert banana    90    172.3753
26232   North     Gicumbi   Dessert banana   Dessert banana    87    273.1519
11421   South     Muhanga  Banana for beer  Banana for beer   829    683.1803
1562   Kigali  Nyarugenge  Banana for beer  Banana for beer   800    60.13324
30882    East     Gatsibo          Cassava          Cassava    80    289.2486
14015    West     Karongi  Banana for beer  Banana for beer    80    195.8738
14019    West     Karongi  Banana for beer  Banana for beer    80    407.8138
10341   South     Ruhango  Banana for beer  Banana for beer    80    205.2849

s2q48: 2435 values above the IQR investigation threshold (0.00)

        s1q1       s1q2       s2q4 CropCategory s2q48 plot_weight
29543   East  Nyagatare      Maize        Maize   950    229.8757
29531   East  Nyagatare      Maize        Maize   950    387.7949
31053   East    Gatsibo      Maize        Maize    95    231.6445
887     East    Gatsibo      Maize        Maize   900           1
13310  South    Kamonyi  Bush bean    Bush bean     9    1349.756
13325  South    Kamonyi  Bush bean    Bush bean     9    820.4664
35673   East      Ngoma  Bush bean    Bush bean     9    1064.219
28774   East  Nyagatare      Maize        Maize     9    366.3486
29201   East  Nyagatare      Maize        Maize     9    232.1316
13464  South    Kamonyi  Bush bean    Bush bean     9    1314.897

s2q49: 465 values above the IQR investigation threshold (0.00)

        s1q1       s1q2             s2q4     CropCategory s2q49 plot_weight
278    South    Kamonyi            Maize            Maize    90           1
826     East  Nyagatare       Paddy rice       Paddy rice    90           1
13445  South    Kamonyi            Maize            Maize    80    1209.168
23237  North    Gakenke  Banana for beer  Banana for beer     8     699.104
35680   East      Ngoma    Climbing bean    Climbing bean     8    126.7918
207    South       Huye       Paddy rice       Paddy rice   780           1
153    South   Gisagara       Paddy rice       Paddy rice   700           1
12643  South    Kamonyi            Maize            Maize     7    287.3094
23240  North    Gakenke  Banana for beer  Banana for beer     7    7949.767
12637  South    Kamonyi            Maize            Maize     7    681.7471

s2q50: 344 values above the IQR investigation threshold (0.00)

        s1q1       s1q2          s2q4  CropCategory  s2q50 plot_weight
738     East  Nyagatare    Paddy rice    Paddy rice    900           1
21684  North    Rulindo  Irish potato  Irish potato     90    404.2155
31333   East    Gatsibo       Cassava       Cassava     90    345.0805
676     East  Nyagatare        Pepper    Vegetables     90           1
138    South     Nyanza    Paddy rice    Paddy rice   8740           1
823     East  Nyagatare         Maize         Maize     87           1
824     East  Nyagatare         Maize         Maize     87           1
313     West     Rusizi    Paddy rice    Paddy rice  80000           1
13585  South    Kamonyi       Cassava       Cassava    800     115.725
710     East  Nyagatare    Paddy rice    Paddy rice     80           1

==========================================================================================
DATASET: sas_2024_seasonB_production
==========================================================================================

s2q13_2: 2286 values above the IQR investigation threshold (24.25)

         s1q1        s1q2          s2q4  CropCategory s2q13_2 plot_weight
9843    South     Ruhango       Cassava       Cassava     984    499.3738
1723   Kigali  Nyarugenge       Cassava       Cassava     983    130.4166
4704    South      Nyanza       Cassava       Cassava     982    140.0285
728      East   Nyagatare     Bush bean     Bush bean     980           1
15552    West      Rubavu  Irish potato  Irish potato     980    382.5723
20908   North     Gakenke       Cassava       Cassava      98    1228.205
21668   North     Gakenke       Cassava       Cassava      98    764.6966
17909    West      Rusizi       Cassava       Cassava      98    1092.063
262      West      Rusizi    Paddy rice    Paddy rice     978           1
160     South        Huye    Paddy rice    Paddy rice     975           1

s2q14: 1904 values above the IQR investigation threshold (7.50)

        s1q1       s1q2          s2q4  CropCategory  s2q14 plot_weight
728     East  Nyagatare     Bush bean     Bush bean    980           1
160    South       Huye    Paddy rice    Paddy rice    975           1
336    North    Gicumbi  Irish potato  Irish potato  924.5           1
814     East  Nyagatare     Bush bean     Bush bean    912           1
11670  South    Kamonyi       Cassava       Cassava    900    644.8456
26400   East  Nyagatare     Bush bean     Bush bean     90    252.1542
27186   East  Nyagatare       Sorghum       Sorghum     90    234.5156
22022  North    Musanze  Irish potato  Irish potato     90    777.4349
4609   South     Nyanza        Tomato    Vegetables     90    1103.491
15098   West     Rubavu  Irish potato  Irish potato     90    356.4459

s2q15: 1000 values above the IQR investigation threshold (16250.00)

        s1q1       s1q2          s2q4  CropCategory   s2q15 plot_weight
724     East  Nyagatare       Soybean       Soybean  998400           1
160    South       Huye    Paddy rice    Paddy rice  994500           1
8373   South  Nyamagabe  Irish potato  Irish potato   98000    1460.971
21987  North    Musanze  Irish potato  Irish potato   98000    539.1407
22513  North     Burera  Irish potato  Irish potato  960000    149.8113
8671   South  Nyamagabe  Irish potato  Irish potato   96000    376.6857
15435   West     Rubavu  Irish potato  Irish potato   96000    863.1036
14820   West    Rutsiro  Irish potato  Irish potato   96000    810.2778
643     East  Nyagatare     Bush bean     Bush bean   93500           1
211    South    Ruhango    Paddy rice    Paddy rice   93000           1

s2q16_2: 555 values above the IQR investigation threshold (48.50)

       s1q1       s1q2        s2q4 CropCategory s2q16_2 plot_weight
779    East  Nyagatare  Paddy rice   Paddy rice    9900           1
285   North    Rulindo       Wheat        Wheat     978           1
9079  South    Ruhango     Cassava      Cassava     960    621.2249
706    East  Nyagatare      Pepper   Vegetables      96           1
1206   East   Bugesera  Paddy rice   Paddy rice     950           1
798    East  Nyagatare       Maize        Maize      95           1
968    East    Kayonza  Paddy rice   Paddy rice     928           1
165   South       Huye  Paddy rice   Paddy rice     928           1
700    East  Nyagatare       Maize        Maize      91           1
210   South    Ruhango  Paddy rice   Paddy rice     900           1

s2q17: 536 values above the IQR investigation threshold (28.50)

       s1q1       s1q2        s2q4 CropCategory s2q17 plot_weight
779    East  Nyagatare  Paddy rice   Paddy rice  9900           1
706    East  Nyagatare      Pepper   Vegetables    96           1
1206   East   Bugesera  Paddy rice   Paddy rice   950           1
798    East  Nyagatare       Maize        Maize    95           1
968    East    Kayonza  Paddy rice   Paddy rice   928           1
165   South       Huye  Paddy rice   Paddy rice   928           1
700    East  Nyagatare       Maize        Maize    91           1
156   South       Huye  Paddy rice   Paddy rice   900           1
210   South    Ruhango  Paddy rice   Paddy rice   900           1
245    West     Rusizi       Maize        Maize    90           1

s2q46: 666 values above the IQR investigation threshold (0.00)

,s1q1,s1q2,s2q4,CropCategory,s2q46,plot_weight
21526,North,Gakenke,Irish potato,Irish potato,9,261.9522
801,East,Nyagatare,Irish potato,Irish potato,800,1
15776,West,Nyabihu,Irish potato,Irish potato,800,274.022
15552,West,Rubavu,Irish potato,Irish potato,80,382.5723
284,North,Rulindo,Climbing bean,Climbing bean,8,1
20326,North,Rulindo,Other fodder crop (specify),Fodder crops,8,544.8659
6267,South,Gisagara,Tomato,Vegetables,8,1963.616
12300,South,Kamonyi,Tomato,Vegetables,8,837.5122
20942,North,Gakenke,Sweet potato,Sweet potato,8,738.1103
291,North,Rulindo,Climbing bean,Climbing bean,8,1

s2q47: 108 negative records

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q8,s1q9,...,s4q6,s4q8,s4q9,s4q10_1,s4q11_1,s4q12_1,s4q14,s4q15,s5q12,plot_weight
118,119,22013,South,Gisagara,Large Scale Farmer/LSF,13,13,Large scale farmer as Coperative/Company/Asso...,<NA>,<NA>,...,Yes,No,<NA>,<NA>,<NA>,<NA>,No,<NA>,19/07/2024,1
158,159,24012,South,Huye,Large Scale Farmer/LSF,12,12,Large scale farmer as Coperative/Company/Asso...,<NA>,<NA>,...,Yes,No,<NA>,<NA>,<NA>,<NA>,Yes,Yes,19/07/2024,1
628,629,52005,East,Nyagatare,Large Scale Farmer/LSF,5,1,Large scale farmer as individual,Male,75,...,No,Yes,No,<NA>,<NA>,<NA>,No,<NA>,06/07/2024,1
633,634,52005,East,Nyagatare,Large Scale Farmer/LSF,5,1,Large scale farmer as individual,Male,75,...,No,Yes,Yes,No,Yes,No,Yes,No,06/07/2024,1
637,638,52005,East,Nyagatare,Large Scale Farmer/LSF,5,1,Large scale farmer as individual,Male,75,...,No,No,<NA>,<NA>,<NA>,<NA>,Yes,No,06/07/2024,1
639,640,52005,East,Nyagatare,Large Scale Farmer/LSF,5,1,Large scale farmer as individual,Male,75,...,No,Yes,No,<NA>,<NA>,<NA>,Yes,No,06/07/2024,1
641,642,52005,East,Nyagatare,Large Scale Farmer/LSF,5,1,Large scale farmer as individual,Male,75,...,No,Yes,Yes,No,Yes,No,Yes,No,06/07/2024,1
643,644,52005,East,Nyagatare,Large Scale Farmer/LSF,5,1,Large scale farmer as individual,Male,75,...,No,Yes,Yes,No,Yes,No,Yes,Yes,06/07/2024,1
644,645,52005,East,Nyagatare,Large Scale Farmer/LSF,5,1,Large scale farmer as individual,Male,75,...,No,Yes,Yes,No,Yes,No,Yes,No,06/07/2024,1
5171,5172,221009,South,Gisagara,Agricultural land on hillside,9,16,Small scale farmer as individual,Male,48,...,No,No,<NA>,<NA>,<NA>,<NA>,No,<NA>,04/07/2024,151.9267

s2q47: 340 values above the IQR investigation threshold (0.00)

         s1q1        s1q2             s2q4     CropCategory s2q47 plot_weight
20491   North     Rulindo   Dessert banana   Dessert banana    95    488.6546
10648   South     Muhanga  Banana for beer  Banana for beer    90    499.6098
10308   South     Muhanga  Banana for beer  Banana for beer    90    301.0744
7651    South        Huye   Dessert banana   Dessert banana    90    416.3455
3058   Kigali    Kicukiro  Banana for beer  Banana for beer    90    40.73548
16558    West   Ngororero  Banana for beer  Banana for beer     9    334.1306
1741   Kigali  Nyarugenge          Cassava          Cassava     9    74.29195
16556    West   Ngororero  Banana for beer  Banana for beer     9    220.5865
3209   Kigali    Kicukiro          Cassava          Cassava     9    36.25747
3207   Kigali    Kicukiro          Cassava          Cassava     9    30.01577

s2q48: 1567 values above the IQR investigation threshold (0.00)

        s1q1       s1q2        s2q4 CropCategory  s2q48 plot_weight
118    South   Gisagara  Paddy rice   Paddy rice  95492           1
967     East    Kayonza  Paddy rice   Paddy rice   9391           1
105    South     Nyanza  Paddy rice   Paddy rice    924           1
538     East  Rwamagana  Paddy rice   Paddy rice   9000           1
1162    East      Ngoma   Bush bean    Bush bean     90           1
32472   East      Ngoma     Cassava      Cassava      9    171.8052
27734   East    Gatsibo   Bush bean    Bush bean      9    470.6033
1093    East      Ngoma    Amaranth   Vegetables     85           1
1089    East      Ngoma    Amaranth   Vegetables     85           1
1102    East      Ngoma    Amaranth   Vegetables     85           1

s2q49: 313 values above the IQR investigation threshold (0.00)

        s1q1       s1q2             s2q4  CropCategory s2q49 plot_weight
163    South       Huye       Paddy rice    Paddy rice   768           1
25625   East  Rwamagana        Pineapple        Fruits    75    29.95877
13006  South    Kamonyi           Tomato    Vegetables   700    189.4238
6267   South   Gisagara           Tomato    Vegetables     7    1963.616
32701   East      Ngoma           Tomato    Vegetables    60    883.1169
34214   East   Bugesera           Tomato    Vegetables     6    1211.458
10855  South    Muhanga     Sweet potato  Sweet potato     6    310.9464
202    South    Ruhango       Paddy rice    Paddy rice   501           1
1073    East     Kirehe       Paddy rice    Paddy rice  5000           1
20516  North    Rulindo  French beans       Vegetables   500    49.69567

s2q50: 217 values above the IQR investigation threshold (0.00)

         s1q1       s1q2             s2q4     CropCategory s2q50 plot_weight
16472    West  Ngororero     Sweet potato     Sweet potato     8    5210.859
16713    West  Ngororero     Sweet potato     Sweet potato     8    1124.072
19743   North    Rulindo  Banana for beer  Banana for beer     8    684.7597
2007   Kigali     Gasabo         Eggplant       Vegetables     8    161.7148
104     South     Nyanza       Paddy rice       Paddy rice  7500           1
1073     East     Kirehe       Paddy rice       Paddy rice  7000           1
13006   South    Kamonyi           Tomato       Vegetables   700    189.4238
17108    West  Ngororero     Irish potato     Irish potato     7    1386.883
17109    West  Ngororero     Irish potato     Irish potato     7    555.9609
18395    West     Rusizi   Dessert banana   Dessert banana   600    470.2822

==========================================================================================
DATASET: sas_2024_seasonC_production
==========================================================================================

s2q13_2: 100 values above the IQR investigation threshold (195.50)

       s1q1     s1q2          s2q4  CropCategory s2q13_2 plot_weight
998    West  Nyabihu  Irish potato  Irish potato     900   100.45824
889    West  Rutsiro  Irish potato  Irish potato     900   32.558098
888    West  Rutsiro  Irish potato  Irish potato     820   43.768721
1314  North  Musanze  Irish potato  Irish potato     820   63.072203
1346  North  Musanze  Irish potato  Irish potato     800   0.6163055
1486  North  Gicumbi  Irish potato  Irish potato     800   86.670898
1289  North  Musanze  Irish potato  Irish potato     800   124.28344
1323  North  Musanze  Irish potato  Irish potato   755.5   244.61336
1286  North  Musanze  Irish potato  Irish potato     750   101.07694
902    West  Rutsiro  Irish potato  Irish potato     740   51.955914

s2q14: 144 values above the IQR investigation threshold (63.50)

       s1q1     s1q2          s2q4  CropCategory s2q14 plot_weight
1303  North  Musanze  Irish potato  Irish potato  91.9   759.68146
889    West  Rutsiro  Irish potato  Irish potato   900   32.558098
1454  North   Burera  Irish potato  Irish potato    90   180.18202
1024   West  Nyabihu  Irish potato  Irish potato  89.8   722.06322
961    West  Nyabihu  Irish potato  Irish potato  85.2   761.46026
1029   West  Nyabihu  Irish potato  Irish potato    85   459.29864
1406  North   Burera  Irish potato  Irish potato    85   84.486189
1314  North  Musanze  Irish potato  Irish potato   820   63.072203
1462  North   Burera  Irish potato  Irish potato    82   109.35131
1346  North  Musanze  Irish potato  Irish potato   800   0.6163055

s2q15: 210 values above the IQR investigation threshold (29750.00)

       s1q1     s1q2          s2q4  CropCategory   s2q15 plot_weight
1446  North   Burera  Irish potato  Irish potato   96000   95.643167
1202  North  Rulindo  Irish potato  Irish potato   96000   89.394896
1396  North   Burera  Irish potato  Irish potato   90000   834.95578
1345  North  Musanze  Irish potato  Irish potato   90000  0.48384863
1312  North  Musanze  Irish potato  Irish potato  880000   97.595666
937    West   Rubavu  Irish potato  Irish potato   86000   543.74251
1029   West  Nyabihu  Irish potato  Irish potato   85000   459.29864
1031   West  Nyabihu  Irish potato  Irish potato   84000   241.24583
962    West  Nyabihu  Irish potato  Irish potato   84000   795.42771
1332  North  Musanze       Cabbage    Vegetables   84000   283.79604

s2q16_2: 31 values above the IQR investigation threshold (337.50)

        s1q1      s1q2             s2q4  CropCategory s2q16_2 plot_weight
1013    West   Nyabihu     Irish potato  Irish potato   839.2   77.267053
990     West   Nyabihu     Irish potato  Irish potato     700   140.58599
1011    West   Nyabihu     Irish potato  Irish potato     600   181.90947
1010    West   Nyabihu     Irish potato  Irish potato     500   203.86721
1732    East    Kirehe            Onion    Vegetables     500   367.19568
1632    East   Gatsibo            Onion    Vegetables     500   177.93413
111   Kigali  Kicukiro  French beans       Vegetables     500   26.448741
1005    West   Nyabihu     Irish potato  Irish potato     500   68.713578
1723    East   Kayonza           Tomato    Vegetables     500   110.36221
932     West    Rubavu          Cabbage    Vegetables     500   447.37809

s2q17: 31 values above the IQR investigation threshold (343.80)

        s1q1      s1q2             s2q4  CropCategory  s2q17 plot_weight
1013    West   Nyabihu     Irish potato  Irish potato  839.2   77.267053
990     West   Nyabihu     Irish potato  Irish potato    700   140.58599
1011    West   Nyabihu     Irish potato  Irish potato    600   181.90947
1010    West   Nyabihu     Irish potato  Irish potato    500   203.86721
1732    East    Kirehe            Onion    Vegetables    500   367.19568
1632    East   Gatsibo            Onion    Vegetables    500   177.93413
111   Kigali  Kicukiro  French beans       Vegetables    500   26.448741
1005    West   Nyabihu     Irish potato  Irish potato    500   68.713578
1723    East   Kayonza           Tomato    Vegetables    500   110.36221
932     West    Rubavu          Cabbage    Vegetables    500   447.37809

s2q46: 75 values above the IQR investigation threshold (0.00)

       s1q1      s1q2          s2q4  CropCategory s2q46 plot_weight
1858   East  Bugesera        Tomato    Vegetables    80    95.98569
1851   East  Bugesera        Tomato    Vegetables    68   199.18677
641   South   Ruhango        Tomato    Vegetables    60   232.95329
944    West    Rubavu      Eggplant    Vegetables    58   6.0245671
1739   East    Kirehe        Tomato    Vegetables    57   58.250215
1207  North   Rulindo        Tomato    Vegetables    50    173.9026
338   South  Gisagara        Tomato    Vegetables    50   225.22203
770   South   Kamonyi        Tomato    Vegetables    50   336.18576
1735   East    Kirehe        Tomato    Vegetables    50   61.342786
1503  North   Gicumbi  Irish potato  Irish potato    50   134.69709

s2q47: 6 negative records

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q8,s1q9,...,s4q6,s4q8,s4q9,s4q10_1,s4q11_1,s4q12_1,s4q14,s4q15,s5q12,plot_weight
37,38,112006,Kigali,Nyarugenge,Agricultural land in marshland,6,4,Small scale farmer as individual,Male,30,...,No,No,<NA>,<NA>,<NA>,<NA>,Yes,Yes,30/09/2024,69.911163
176,177,212019,South,Nyanza,Agricultural land in marshland,19,8,Small scale farmer as individual,Male,40,...,No,No,<NA>,<NA>,<NA>,<NA>,Yes,Yes,03/10/2024,233.61867
488,489,242033,South,Huye,Agricultural land in marshland,33,4,Small scale farmer as individual,Male,44,...,No,No,<NA>,<NA>,<NA>,<NA>,No,<NA>,04/10/2024,629.49895
1507,1508,452012,North,Gicumbi,Agricultural land in marshland,12,3,Small scale farmer as individual,Female,60,...,No,No,<NA>,<NA>,<NA>,<NA>,No,<NA>,01/10/2024,236.18894
1739,1740,551007,East,Kirehe,Agricultural land on hillside,7,7,Small scale farmer as individual,Male,21,...,No,No,<NA>,<NA>,<NA>,<NA>,Yes,Yes,01/10/2024,58.250215
1761,1762,552010,East,Kirehe,Agricultural land in marshland,10,1,Small scale farmer as individual,Male,72,...,No,No,<NA>,<NA>,<NA>,<NA>,Yes,Yes,02/10/2024,40.089307

s2q47: 25 values above the IQR investigation threshold (0.00)

       s1q1       s1q2          s2q4  CropCategory s2q47 plot_weight
1587   East  Nyagatare        Tomato    Vegetables    80   74.651116
1446  North     Burera  Irish potato  Irish potato    80   95.643167
1404  North     Burera  Irish potato  Irish potato    80   1834.6693
659   South    Ruhango  Sweet potato  Sweet potato    72     1324.17
661   South    Ruhango  Sweet potato  Sweet potato    72   2677.5413
483   South       Huye  Sweet potato  Sweet potato    70   212.89473
795   South    Kamonyi        Tomato    Vegetables     7   132.22381
1913   East   Bugesera         Onion    Vegetables     5   288.49766
1912   East   Bugesera         Onion    Vegetables     5   375.57176
639   South    Ruhango  Sweet potato  Sweet potato     5   428.58437

s2q48: 37 values above the IQR investigation threshold (0.00)

        s1q1        s1q2          s2q4  CropCategory s2q48 plot_weight
37    Kigali  Nyarugenge        Tomato    Vegetables     8   69.911163
197    South      Nyanza  Sweet potato  Sweet potato     7   670.81413
1735    East      Kirehe        Tomato    Vegetables    50   61.342786
41    Kigali  Nyarugenge        Tomato    Vegetables    50   71.610583
306    South    Gisagara        Tomato    Vegetables    50   305.45003
1444   North      Burera  Irish potato  Irish potato     5   349.60605
1873    East    Bugesera     Bush bean     Bush bean     5   142.86794
1863    East    Bugesera     Bush bean     Bush bean     5   152.21717
319    South    Gisagara     Bush bean     Bush bean     5   167.39224
1867    East    Bugesera     Bush bean     Bush bean     5   39.116053

s2q49: 46 values above the IQR investigation threshold (0.00)

        s1q1        s1q2          s2q4  CropCategory s2q49 plot_weight
39    Kigali  Nyarugenge        Tomato    Vegetables    98   65.357009
37    Kigali  Nyarugenge        Tomato    Vegetables     8   69.911163
1627    East     Gatsibo       Cabbage    Vegetables     7   115.36067
246    South    Gisagara        Tomato    Vegetables    58   663.89769
1848    East       Ngoma        Tomato    Vegetables    57   69.215192
1903    East    Bugesera        Tomato    Vegetables    50    786.1687
1744    East      Kirehe  Sweet pepper    Vegetables     5   20.222146
789    South     Kamonyi         Onion    Vegetables     5   115.58386
15    Kigali  Nyarugenge  Irish potato  Irish potato     5   176.24235
57    Kigali      Gasabo       Cabbage    Vegetables     5   85.066657

s2q50: 54 values above the IQR investigation threshold (0.00)

       s1q1      s1q2          s2q4  CropCategory s2q50 plot_weight
766   South   Kamonyi        Tomato    Vegetables    80   178.44631
290   South  Gisagara  Sweet potato  Sweet potato    80    192.6913
1253  North   Gakenke  Irish potato  Irish potato     7   36.707083
772   South   Kamonyi        Tomato    Vegetables     7   279.20072
166   South    Nyanza        Pepper    Vegetables   674   39.644705
1733   East    Kirehe        Tomato    Vegetables   600   48.989024
1357  North   Musanze  Sweet potato  Sweet potato    60   126.40001
146   South    Nyanza        Tomato    Vegetables     6   411.14109
843   South   Kamonyi  Sweet potato  Sweet potato     5   149.92123
789   South   Kamonyi         Onion    Vegetables     5   115.58386

In [21]:

import pandas as pd

variables_to_check = [
    "s2q13_2", "s2q14", "s2q15",
    "s2q16_2", "s2q17",
    "s2q46", "s2q47", "s2q48", "s2q49", "s2q50"
]

for dataset_name, df in final_cleaned_datasets.items():
    if "production" not in dataset_name.lower():
        continue

    print(f"\n{'=' * 75}\n{dataset_name}\n{'=' * 75}")

    for col in variables_to_check:
        if col not in df.columns:
            continue

        original = df[col]
        numeric = pd.to_numeric(original, errors="coerce")

        print(f"\n{col}")
        print("Original Python types:")
        print(original.dropna().map(type).value_counts().head())

        print("Most frequent original values:")
        display(original.value_counts(dropna=False).head(12).to_frame("Count"))

        print("Most frequent numeric values:")
        display(numeric.value_counts(dropna=False).head(12).to_frame("Count"))

        # Show negative records with useful context.
        negative_mask = numeric < 0

        if negative_mask.any():
            context_cols = [
                c for c in [
                    "id", "Segment_ID", "s1q1", "s1q2",
                    "s2q4", col, "s5q12", "plot_weight"
                ]
                if c in df.columns
            ]

            print(f"Negative records: {int(negative_mask.sum())}")
            display(df.loc[negative_mask, context_cols].head(15))

===========================================================================
sas_2024_seasonA_production
===========================================================================

s2q13_2
Original Python types:
s2q13_2
<class 'str'>    19879
Name: count, dtype: int64
Most frequent original values:

         Count
s2q13_2
<NA>     19451
3         1508
2         1442
1         1431
5          978
0.5        884
4          880
10         784
6          741
1.5        705
15         524
8          430

Most frequent numeric values:

         Count
s2q13_2
NaN      19451
3.0       1508
2.0       1442
1.0       1431
5.0        978
0.5        884
4.0        880
10.0       784
6.0        741
1.5        705
15.0       524
8.0        430

s2q14
Original Python types:
s2q14
<class 'str'>    19871
Name: count, dtype: int64
Most frequent original values:

       Count
s2q14
<NA>   19459
0      11947
3        784
2        657
1        598
5        469
4        430
6        407
1.5      366
10       364
0.5      303
15       226

Most frequent numeric values:

       Count
s2q14
NaN    19459
0.0    11947
3.0      784
2.0      657
1.0      598
5.0      469
4.0      430
6.0      407
1.5      366
10.0     364
0.5      303
15.0     226

s2q15
Original Python types:
s2q15
<class 'str'>    11617
Name: count, dtype: int64
Most frequent original values:

       Count
s2q15
<NA>   27713
0       2933
6000     476
2000     398
3000     380
4000     290
12000    282
1000     238
10000    238
1500     230
5000     218
8000     213

Most frequent numeric values:

         Count
s2q15
NaN      27713
0.0       2933
6000.0     476
2000.0     398
3000.0     380
4000.0     290
12000.0    282
1000.0     238
10000.0    238
1500.0     230
5000.0     218
8000.0     213

s2q16_2
Original Python types:
s2q16_2
<class 'str'>    6094
Name: count, dtype: int64
Most frequent original values:

         Count
s2q16_2
<NA>     33236
1          972
2          917
0.5        735
1.5        356
4          343
0.25       306
3          290
6          146
250        107
500         94
5           85

Most frequent numeric values:

         Count
s2q16_2
NaN      33236
1.00       972
2.00       917
0.50       735
1.50       356
4.00       343
0.25       306
3.00       290
6.00       146
250.00     107
500.00      94
5.00        85

s2q17
Original Python types:
s2q17
<class 'str'>    6094
Name: count, dtype: int64
Most frequent original values:

       Count
s2q17
<NA>   33236
1        954
2        906
0.5      722
1.5      350
4        332
0.25     297
3        292
0        186
6        139
250      101
500       93

Most frequent numeric values:

        Count
s2q17
NaN     33236
1.00      954
2.00      906
0.50      722
1.50      350
4.00      332
0.25      297
3.00      292
0.00      186
6.00      139
250.00    101
500.00     93

s2q46
Original Python types:
s2q46
<class 'str'>    34349
Name: count, dtype: int64
Most frequent original values:

       Count
s2q46
0      33330
<NA>    4981
1        272
2        140
5         90
3         66
10        66
20        53
50        27
100       24
200       22
4         22

Most frequent numeric values:

       Count
s2q46
0.0    33330
NaN     4981
1.0      272
2.0      140
5.0       90
3.0       66
10.0      66
20.0      53
50.0      27
100.0     24
200.0     22
4.0       22

s2q47
Original Python types:
s2q47
<class 'str'>    34349
Name: count, dtype: int64
Most frequent original values:

       Count
s2q47
0      33880
<NA>    4981
-1       121
5         25
2         22
1         22
100       20
30        17
-2        17
10        17
200       16
50        12

Most frequent numeric values:

        Count
s2q47
 0.0    33880
 NaN     4981
-1.0      121
 5.0       25
 2.0       22
 1.0       22
 100.0     20
 30.0      17
-2.0       17
 10.0      17
 200.0     16
 50.0      12

Negative records: 142

,id,Segment_ID,s1q1,s1q2,s2q4,s2q47,s5q12,plot_weight
148,149,22004,South,Gisagara,Maize,-340,19/02/2024,1
151,152,22010,South,Gisagara,Paddy rice,-1,21/02/2024,1
739,740,52022,East,Nyagatare,Maize,-1,05/03/2024,1
742,743,52022,East,Nyagatare,Maize,-1,05/03/2024,1
5421,5422,221009,South,Gisagara,Maize,-1,26/01/2024,251.4092
5423,5424,221009,South,Gisagara,Bush bean,-1,26/01/2024,251.4092
5437,5438,221009,South,Gisagara,Maize,-1,26/01/2024,304.0784
5438,5439,221009,South,Gisagara,Bush bean,-1,26/01/2024,304.0784
5449,5450,221009,South,Gisagara,Maize,-1,26/01/2024,231.2164
5450,5451,221009,South,Gisagara,Bush bean,-1,26/01/2024,231.2164
5476,5477,221011,South,Gisagara,Bush bean,-1,29/01/2024,225.1638
5538,5539,221011,South,Gisagara,Bush bean,-1,29/01/2024,1665.99
5672,5673,221015,South,Gisagara,Maize,-1,31/01/2024,752.9597
5802,5803,221019,South,Gisagara,Sorghum,-1,05/02/2024,292.3055
5919,5920,221022,South,Gisagara,Maize,-1,24/02/2024,2016.883

s2q48
Original Python types:
s2q48
<class 'str'>    34349
Name: count, dtype: int64
Most frequent original values:

       Count
s2q48
0      31914
<NA>    4981
1        464
2        357
5        293
3        214
10       165
20       125
4         84
30        66
50        60
15        55

Most frequent numeric values:

       Count
s2q48
0.0    31914
NaN     4981
1.0      464
2.0      357
5.0      293
3.0      214
10.0     165
20.0     125
4.0       84
30.0      66
50.0      60
15.0      55

s2q49
Original Python types:
s2q49
<class 'str'>    34349
Name: count, dtype: int64
Most frequent original values:

       Count
s2q49
0      33884
<NA>    4981
1        144
2         48
5         45
3         41
500       33
100       28
10        20
20        17
50        10
200        7

Most frequent numeric values:

       Count
s2q49
0.0    33884
NaN     4981
1.0      144
2.0       48
5.0       45
3.0       41
500.0     33
100.0     28
10.0      20
20.0      17
50.0      10
200.0      7

s2q50
Original Python types:
s2q50
<class 'str'>    34349
Name: count, dtype: int64
Most frequent original values:

       Count
s2q50
0      34005
<NA>    4981
1         57
10        34
2         32
100       31
5         31
20        26
500       16
30        11
3         11
50        10

Most frequent numeric values:

       Count
s2q50
0.0    34005
NaN     4981
1.0       57
10.0      34
2.0       32
100.0     31
5.0       31
20.0      26
500.0     16
30.0      11
3.0       11
50.0      10

===========================================================================
sas_2024_seasonB_production
===========================================================================

s2q13_2
Original Python types:
s2q13_2
<class 'str'>    15883
Name: count, dtype: int64
Most frequent original values:

         Count
s2q13_2
<NA>     19701
3         1403
2         1319
1         1311
5          877
4          831
0.5        700
10         653
6          610
1.5        576
15         402
8          376

Most frequent numeric values:

         Count
s2q13_2
NaN      19701
3.0       1403
2.0       1319
1.0       1311
5.0        877
4.0        831
0.5        700
10.0       653
6.0        610
1.5        576
15.0       402
8.0        376

s2q14
Original Python types:
s2q14
<class 'str'>    15878
Name: count, dtype: int64
Most frequent original values:

       Count
s2q14
<NA>   19706
0       9854
3        627
2        596
1        484
5        385
4        376
10       268
6        260
1.5      239
0.5      170
8        152

Most frequent numeric values:

       Count
s2q14
NaN    19706
0.0     9854
3.0      627
2.0      596
1.0      484
5.0      385
4.0      376
10.0     268
6.0      260
1.5      239
0.5      170
8.0      152

s2q15
Original Python types:
s2q15
<class 'str'>    9026
Name: count, dtype: int64
Most frequent original values:

       Count
s2q15
<NA>   26558
0       2554
3000     371
2000     330
4000     298
1000     291
6000     264
5000     239
2400     192
8000     153
12000    152
10000    150

Most frequent numeric values:

         Count
s2q15
NaN      26558
0.0       2554
3000.0     371
2000.0     330
4000.0     298
1000.0     291
6000.0     264
5000.0     239
2400.0     192
8000.0     153
12000.0    152
10000.0    150

s2q16_2
Original Python types:
s2q16_2
<class 'str'>    2657
Name: count, dtype: int64
Most frequent original values:

         Count
s2q16_2
<NA>     32927
1          389
2          362
0.5        312
4          146
3          129
1.5        122
0.25        99
6           64
250         61
500         52
50          48

Most frequent numeric values:

         Count
s2q16_2
NaN      32927
1.00       389
2.00       362
0.50       312
4.00       146
3.00       129
1.50       122
0.25        99
6.00        64
250.00      61
500.00      52
50.00       48

s2q17
Original Python types:
s2q17
<class 'str'>    2657
Name: count, dtype: int64
Most frequent original values:

       Count
s2q17
<NA>   32927
1        384
2        361
0.5      301
4        147
3        128
0        127
1.5      122
0.25      96
6         63
250       59
500       50

Most frequent numeric values:

        Count
s2q17
NaN     32927
1.00      384
2.00      361
0.50      301
4.00      147
3.00      128
0.00      127
1.50      122
0.25       96
6.00       63
250.00     59
500.00     50

s2q46
Original Python types:
s2q46
<class 'str'>    34679
Name: count, dtype: int64
Most frequent original values:

       Count
s2q46
0      34013
<NA>     905
1        220
2         91
5         51
10        51
20        40
3         34
15        27
50        18
100       16
30        13

Most frequent numeric values:

       Count
s2q46
0.0    34013
NaN      905
1.0      220
2.0       91
5.0       51
10.0      51
20.0      40
3.0       34
15.0      27
50.0      18
100.0     16
30.0      13

s2q47
Original Python types:
s2q47
<class 'str'>    34679
Name: count, dtype: int64
Most frequent original values:

       Count
s2q47
0      34231
<NA>     905
-1        94
20        27
10        25
5         20
30        17
15        16
50        16
60        14
100       13
200       11

Most frequent numeric values:

        Count
s2q47
 0.0    34231
 NaN      905
-1.0       94
 20.0      27
 10.0      25
 5.0       20
 30.0      17
 15.0      16
 50.0      16
 60.0      14
 100.0     13
 200.0     11

Negative records: 108

,id,Segment_ID,s1q1,s1q2,s2q4,s2q47,s5q12,plot_weight
118,119,22013,South,Gisagara,Paddy rice,-2,19/07/2024,1
158,159,24012,South,Huye,Paddy rice,-1,19/07/2024,1
628,629,52005,East,Nyagatare,Bush bean,-1,06/07/2024,1
633,634,52005,East,Nyagatare,Bush bean,-1,06/07/2024,1
637,638,52005,East,Nyagatare,Bush bean,-1,06/07/2024,1
639,640,52005,East,Nyagatare,Bush bean,-1,06/07/2024,1
641,642,52005,East,Nyagatare,Bush bean,-1,06/07/2024,1
643,644,52005,East,Nyagatare,Bush bean,-1,06/07/2024,1
644,645,52005,East,Nyagatare,Bush bean,-1,06/07/2024,1
5171,5172,221009,South,Gisagara,Maize,-1,04/07/2024,151.9267
5228,5229,221011,South,Gisagara,Bush bean,-1,29/06/2024,2873.289
5255,5256,221012,South,Gisagara,Sorghum,-1,01/07/2024,395.7483
5288,5289,221012,South,Gisagara,Bush bean,-1,01/07/2024,744.7618
5300,5301,221012,South,Gisagara,Sorghum,-1,01/07/2024,232.8709
5315,5316,221013,South,Gisagara,Soybean,-1,21/06/2024,435.5573

s2q48
Original Python types:
s2q48
<class 'str'>    34679
Name: count, dtype: int64
Most frequent original values:

       Count
s2q48
0      33112
<NA>     905
1        516
2        294
5        154
3        153
10        79
20        49
4         39
15        31
30        23
50        20

Most frequent numeric values:

       Count
s2q48
0.0    33112
NaN      905
1.0      516
2.0      294
5.0      154
3.0      153
10.0      79
20.0      49
4.0       39
15.0      31
30.0      23
50.0      20

s2q49
Original Python types:
s2q49
<class 'str'>    34679
Name: count, dtype: int64
Most frequent original values:

       Count
s2q49
0      34366
<NA>     905
1         95
2         44
5         38
10        22
3         19
20        13
200       13
300       13
50        12
25         5

Most frequent numeric values:

       Count
s2q49
0.0    34366
NaN      905
1.0       95
2.0       44
5.0       38
10.0      22
3.0       19
20.0      13
200.0     13
300.0     13
50.0      12
25.0       5

s2q50
Original Python types:
s2q50
<class 'str'>    34679
Name: count, dtype: int64
Most frequent original values:

       Count
s2q50
0      34462
<NA>     905
1         33
5         24
2         23
10        21
100       19
3         16
50         9
15         7
500        7
200        5

Most frequent numeric values:

       Count
s2q50
0.0    34462
NaN      905
1.0       33
5.0       24
2.0       23
10.0      21
100.0     19
3.0       16
50.0       9
15.0       7
500.0      7
200.0      5

===========================================================================
sas_2024_seasonC_production
===========================================================================

s2q13_2
Original Python types:
s2q13_2
<class 'str'>    818
Name: count, dtype: int64
Most frequent original values:

         Count
s2q13_2
<NA>      1131
2           35
10          29
100         28
1           28
3           26
20          24
50          23
1.5         21
4           19
30          19
40          17

Most frequent numeric values:

         Count
s2q13_2
NaN       1131
2.0         35
10.0        29
100.0       28
1.0         28
3.0         26
20.0        24
50.0        23
1.5         21
4.0         19
30.0        19
40.0        17

s2q14
Original Python types:
s2q14
<class 'str'>    817
Name: count, dtype: int64
Most frequent original values:

       Count
s2q14
<NA>    1132
0        343
3         24
2         22
100       20
20        19
1         17
4         16
40        14
50        13
80        13
10        13

Most frequent numeric values:

       Count
s2q14
NaN     1132
0.0      343
3.0       24
2.0       22
100.0     20
20.0      19
1.0       17
4.0       16
40.0      14
50.0      13
80.0      13
10.0      13

s2q15
Original Python types:
s2q15
<class 'str'>    1265
Name: count, dtype: int64
Most frequent original values:

       Count
s2q15
<NA>     684
0        564
3000      40
10000     39
5000      29
6000      27
8000      27
2000      24
20000     20
4000      19
12000     17
1500      13

Most frequent numeric values:

         Count
s2q15
NaN        684
0.0        564
3000.0      40
10000.0     39
5000.0      29
6000.0      27
8000.0      27
2000.0      24
20000.0     20
4000.0      19
12000.0     17
1500.0      13

s2q16_2
Original Python types:
s2q16_2
<class 'str'>    305
Name: count, dtype: int64
Most frequent original values:

         Count
s2q16_2
<NA>      1644
50          44
100         38
250         19
25          17
150         17
500         14
10          13
20          12
200         12
30          11
1            7

Most frequent numeric values:

         Count
s2q16_2
NaN       1644
50.0        44
100.0       38
250.0       19
25.0        17
150.0       17
500.0       14
10.0        13
20.0        12
200.0       12
30.0        11
1.0          7

s2q17
Original Python types:
s2q17
<class 'str'>    305
Name: count, dtype: int64
Most frequent original values:

       Count
s2q17
<NA>    1644
50        42
100       38
250       19
150       17
25        17
500       14
10        13
200       12
20        12
30        11
0          7

Most frequent numeric values:

       Count
s2q17
NaN     1644
50.0      42
100.0     38
250.0     19
150.0     17
25.0      17
500.0     14
10.0      13
200.0     12
20.0      12
30.0      11
0.0        7

s2q46
Original Python types:
s2q46
<class 'str'>    1949
Name: count, dtype: int64
Most frequent original values:

       Count
s2q46
0       1874
10         8
3          7
1          7
5          7
2          6
50         6
20         5
30         5
15         4
40         3
200        3

Most frequent numeric values:

       Count
s2q46
0       1874
10         8
3          7
1          7
5          7
2          6
50         6
20         5
30         5
15         4
40         3
200        3

s2q47
Original Python types:
s2q47
<class 'str'>    1949
Name: count, dtype: int64
Most frequent original values:

       Count
s2q47
0       1918
-1         5
10         4
5          3
150        3
80         3
72         2
40         2
20         1
7          1
70         1
30         1

Most frequent numeric values:

       Count
s2q47
 0      1918
-1         5
 10        4
 5         3
 150       3
 80        3
 72        2
 40        2
 20        1
 7         1
 70        1
 30        1

Negative records: 6

,id,Segment_ID,s1q1,s1q2,s2q4,s2q47,s5q12,plot_weight
37,38,112006,Kigali,Nyarugenge,Tomato,-1,30/09/2024,69.911163
176,177,212019,South,Nyanza,Bush bean,-1,03/10/2024,233.61867
488,489,242033,South,Huye,Sweet potato,-1,04/10/2024,629.49895
1507,1508,452012,North,Gicumbi,Soybean,-2,01/10/2024,236.18894
1739,1740,551007,East,Kirehe,Tomato,-1,01/10/2024,58.250215
1761,1762,552010,East,Kirehe,Cabbage,-1,02/10/2024,40.089307

s2q48
Original Python types:
s2q48
<class 'str'>    1949
Name: count, dtype: int64
Most frequent original values:

       Count
s2q48
0       1912
1         11
2          5
5          5
3          4
50         3
20         3
240        1
8          1
7          1
30         1
15         1

Most frequent numeric values:

       Count
s2q48
0       1912
1         11
2          5
5          5
3          4
50         3
20         3
240        1
8          1
7          1
30         1
15         1

s2q49
Original Python types:
s2q49
<class 'str'>    1949
Name: count, dtype: int64
Most frequent original values:

       Count
s2q49
0       1903
10        10
30         5
5          4
2          3
20         3
1          3
45         2
40         2
3          2
4          2
8          1

Most frequent numeric values:

       Count
s2q49
0       1903
10        10
30         5
5          4
2          3
20         3
1          3
45         2
40         2
3          2
4          2
8          1

s2q50
Original Python types:
s2q50
<class 'str'>    1949
Name: count, dtype: int64
Most frequent original values:

       Count
s2q50
0       1895
10         8
20         6
5          5
2          5
100        3
30         3
1          2
306        2
80         2
4          2
3          2

Most frequent numeric values:

       Count
s2q50
0       1895
10         8
20         6
5          5
2          5
100        3
30         3
1          2
306        2
80         2
4          2
3          2

In [22]:

import pandas as pd

variables = [
    "s2q13_2", "s2q14", "s2q15",
    "s2q16_2", "s2q17",
    "s2q46", "s2q47", "s2q48", "s2q49", "s2q50"
]

for name, df in final_cleaned_datasets.items():
    if "production" not in name.lower():
        continue

    print(f"\n{'=' * 70}\n{name}\n{'=' * 70}")

    for col in variables:
        if col not in df.columns:
            continue

        numeric = pd.to_numeric(df[col], errors="coerce")
        negatives = numeric[numeric < 0]

        print(
            f"\n{col}: minimum={numeric.min()}, "
            f"maximum={numeric.max()}, "
            f"negative_count={len(negatives)}"
        )

        if not negatives.empty:
            print("Negative values and frequencies:")
            display(
                negatives.value_counts()
                .sort_index()
                .rename_axis("Negative_Value")
                .to_frame("Count")
            )

======================================================================
sas_2024_seasonA_production
======================================================================

s2q13_2: minimum=0.0, maximum=175000.0, negative_count=0

s2q14: minimum=0.0, maximum=28500.0, negative_count=0

s2q15: minimum=0.0, maximum=4320000.0, negative_count=0

s2q16_2: minimum=0.02, maximum=500000.0, negative_count=0

s2q17: minimum=0.0, maximum=103000.0, negative_count=0

s2q46: minimum=0.0, maximum=62150.0, negative_count=0

s2q47: minimum=-340.0, maximum=5000.0, negative_count=142
Negative values and frequencies:

                Count
Negative_Value
-340.0              1
-6.0                2
-4.0                1
-2.0               17
-1.0              121

s2q48: minimum=0.0, maximum=120000.0, negative_count=0

s2q49: minimum=0.0, maximum=20000.0, negative_count=0

s2q50: minimum=0.0, maximum=80000.0, negative_count=0

======================================================================
sas_2024_seasonB_production
======================================================================

s2q13_2: minimum=0.0, maximum=150000.0, negative_count=0

s2q14: minimum=0.0, maximum=101108.0, negative_count=0

s2q15: minimum=0.0, maximum=121300000.0, negative_count=0

s2q16_2: minimum=0.1, maximum=57065.0, negative_count=0

s2q17: minimum=0.0, maximum=39397.5, negative_count=0

s2q46: minimum=0.0, maximum=38197.0, negative_count=0

s2q47: minimum=-3.0, maximum=1438.0, negative_count=108
Negative values and frequencies:

                Count
Negative_Value
-3.0                3
-2.0               11
-1.0               94

s2q48: minimum=0.0, maximum=280000.0, negative_count=0

s2q49: minimum=0.0, maximum=19099.0, negative_count=0

s2q50: minimum=0.0, maximum=38197.0, negative_count=0

======================================================================
sas_2024_seasonC_production
======================================================================

s2q13_2: minimum=0.0, maximum=2700.0, negative_count=0

s2q14: minimum=0.0, maximum=2000.0, negative_count=0

s2q15: minimum=0.0, maximum=2000000.0, negative_count=0

s2q16_2: minimum=0.5, maximum=2400.0, negative_count=0

s2q17: minimum=0.0, maximum=2400.0, negative_count=0

s2q46: minimum=0, maximum=200, negative_count=0

s2q47: minimum=-2, maximum=380, negative_count=6
Negative values and frequencies:

                Count
Negative_Value
-2                  1
-1                  5

s2q48: minimum=0, maximum=240, negative_count=0

s2q49: minimum=0, maximum=200, negative_count=0

s2q50: minimum=0, maximum=1700, negative_count=0

In [23]:
import pandas as pd
from IPython.display import display

for name, df in final_cleaned_datasets.items():
    if "production" not in name.lower():
        continue

    if "s2q47" not in df.columns:
        continue

    numeric = pd.to_numeric(df["s2q47"], errors="coerce")
    negative_rows = df.loc[numeric < 0].copy()

    if negative_rows.empty:
        continue

    print(f"\n{'=' * 80}")
    print(f"DATASET: {name}")
    print(f"NEGATIVE RECORDS: {len(negative_rows)}")
    print(f"{'=' * 80}")

    # Show identifying and contextual fields where available
    preferred_cols = [
        "id", "Segment_ID", "s1q1", "s1q2",
        "s2q4", "CropCategory", "s2q46", "s2q47",
        "s2q48", "s2q49", "s2q50", "s5q12", "plot_weight"
    ]

    available_cols = [
        col for col in preferred_cols
        if col in negative_rows.columns
    ]

    display(
        negative_rows[available_cols]
        .assign(s2q47_numeric=numeric.loc[negative_rows.index])
        .sort_values("s2q47_numeric")
    )

================================================================================
DATASET: sas_2024_seasonA_production
NEGATIVE RECORDS: 142
================================================================================

,id,Segment_ID,s1q1,s1q2,s2q4,CropCategory,s2q46,s2q47,s2q48,s2q49,s2q50,s5q12,plot_weight,s2q47_numeric
148,149,22004,South,Gisagara,Maize,Maize,100,-340,0,240,0,19/02/2024,1,-340.0
12966,12967,281025,South,Kamonyi,Bush bean,Bush bean,0,-6,6,0,0,16/02/2024,251.9267,-6.0
12990,12991,281025,South,Kamonyi,Bush bean,Bush bean,0,-6,6,0,0,16/02/2024,1088.135,-6.0
12560,12561,281014,South,Kamonyi,Climbing bean,Climbing bean,2,-4,1,1,1,06/02/2024,511.0185,-4.0
12549,12550,281014,South,Kamonyi,Maize,Maize,1,-2,1,1,1,06/02/2024,538.9859,-2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29343,29344,521020,East,Nyagatare,Maize,Maize,1,-1,10,0,0,26/02/2024,1117.903,-1.0
34931,34932,551040,East,Kirehe,Sorghum,Sorghum,1,-1,1,1,0,29/01/2024,170.1435,-1.0
35058,35059,551042,East,Kirehe,Climbing bean,Climbing bean,1,-1,1,1,1,25/01/2024,859.6004,-1.0
35066,35067,551042,East,Kirehe,Climbing bean,Climbing bean,1,-1,1,1,1,25/01/2024,268.8697,-1.0
36184,36185,561018,East,Ngoma,Bush bean,Bush bean,1,-1,1,0,0,30/01/2024,750.1525,-1.0

================================================================================
DATASET: sas_2024_seasonB_production
NEGATIVE RECORDS: 108
================================================================================

,id,Segment_ID,s1q1,s1q2,s2q4,CropCategory,s2q46,s2q47,s2q48,s2q49,s2q50,s5q12,plot_weight,s2q47_numeric
13010,13011,284041,South,Kamonyi,Sorghum,Sorghum,2,-3,1,1,1,24/07/2024,994.4336,-3.0
12982,12983,284040,South,Kamonyi,Sorghum,Sorghum,1,-3,1,1,1,17/07/2024,400.4651,-3.0
12266,12267,281018,South,Kamonyi,Bush bean,Bush bean,2,-3,1,1,1,19/07/2024,468.5673,-3.0
118,119,22013,South,Gisagara,Paddy rice,Paddy rice,38197,-2,95492,19099,38197,19/07/2024,1,-2.0
12268,12269,281018,South,Kamonyi,Bush bean,Bush bean,1,-2,1,0,2,19/07/2024,358.4256,-2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33236,33237,561033,East,Ngoma,Sorghum,Sorghum,1,-1,1,1,0,01/07/2024,510.768,-1.0
33240,33241,561033,East,Ngoma,Sorghum,Sorghum,1,-1,1,1,1,01/07/2024,93.6606,-1.0
33241,33242,561033,East,Ngoma,Sorghum,Sorghum,2,-1,1,1,0,01/07/2024,306.8582,-1.0
33244,33245,561033,East,Ngoma,Sorghum,Sorghum,1,-1,1,0,0,01/07/2024,303.5347,-1.0
33390,33391,561036,East,Ngoma,Bush bean,Bush bean,1,-1,2,0,0,17/07/2024,912.9294,-1.0

================================================================================
DATASET: sas_2024_seasonC_production
NEGATIVE RECORDS: 6
================================================================================

,id,Segment_ID,s1q1,s1q2,s2q4,CropCategory,s2q46,s2q47,s2q48,s2q49,s2q50,s5q12,plot_weight,s2q47_numeric
1507,1508,452012,North,Gicumbi,Soybean,Soybean,1,-2,1,1,0,01/10/2024,236.18894,-2
37,38,112006,Kigali,Nyarugenge,Tomato,Vegetables,15,-1,8,8,17,30/09/2024,69.911163,-1
176,177,212019,South,Nyanza,Bush bean,Bush bean,1,-1,2,0,0,03/10/2024,233.61867,-1
488,489,242033,South,Huye,Sweet potato,Sweet potato,1,-1,3,1,1,04/10/2024,629.49895,-1
1739,1740,551007,East,Kirehe,Tomato,Vegetables,57,-1,0,45,44,01/10/2024,58.250215,-1
1761,1762,552010,East,Kirehe,Cabbage,Vegetables,3,-1,0,0,3,02/10/2024,40.089307,-1

In [25]:

import pandas as pd
from IPython.display import display

df = final_cleaned_datasets["sas_2024_seasonA_production"]

# Find records with negative s2q47 values
negative_mask = pd.to_numeric(
    df["s2q47"], errors="coerce"
) < 0

# Select the unusual -340 record and five -1/-2 examples
extreme = df.loc[
    pd.to_numeric(df["s2q47"], errors="coerce") == -340
]
common = df.loc[
    negative_mask
    & pd.to_numeric(df["s2q47"], errors="coerce").isin([-1, -2])
].head(5)

sample = pd.concat([extreme, common]).drop_duplicates()

# Display only the fields needed for investigation
cols = [
    c for c in [
        "id", "Segment_ID", "s1q1", "s1q2", "s2q4",
        "s2q46", "s2q47", "s2q48", "s2q49", "s2q50"
    ]
    if c in sample.columns
]

display(sample[cols].to_string(index=False))

'  id Segment_ID  s1q1      s1q2       s2q4 s2q46 s2q47 s2q48 s2q49 s2q50\n 149      22004 South  Gisagara      Maize   100  -340     0   240     0\n 152      22010 South  Gisagara Paddy rice  1460    -1  1440    20     0\n 740      52022  East Nyagatare      Maize  1202    -1  1682   241   481\n 743      52022  East Nyagatare      Maize  1202    -1  1682   241   481\n5422     221009 South  Gisagara      Maize     1    -1     0     1     2\n5424     221009 South  Gisagara  Bush bean     1    -1     0     1     1'

In [26]:

df = final_cleaned_datasets["sas_2024_seasonA_production"]

# Compare records by their IDs
ids_to_check = [740, 743]
rows = df.loc[df["id"].isin(ids_to_check)].sort_values("id")

display(rows.T)

# Compare every column, excluding the row identifier
if len(rows) == 2:
    first = rows.iloc[0].drop(labels=["id"], errors="ignore")
    second = rows.iloc[1].drop(labels=["id"], errors="ignore")

    comparable = first.index.intersection(second.index)
    same = first[comparable].eq(second[comparable]) | (
        first[comparable].isna() & second[comparable].isna()
    )

    print("Number of matching non-ID fields:", int(same.sum()))
    print("Number of compared non-ID fields:", len(comparable))
    print("Exact match apart from ID:", bool(same.all()))

    print("\nFields that differ:")
    display(
        pd.DataFrame({
            "record_740": first[comparable],
            "record_743": second[comparable]
        }).loc[~same]
    )

Empty DataFrame
Columns: []
Index: [id, Segment_ID, s1q1, s1q2, s1q3, s1q4, s1q6, s1q7, s1q8, s1q9, s1q14, s2q1, s2q2, s2q3, s2q4, s2q4_o, CropCategory, s2q5, s2q6, s2q7, s2q8, s2q9, s2q10, s2q10_o, s2q11, s2q12, s2q13_1, s2q13_2, s2q14, s2q15, s2q16_1, s2q16_2, s2q17, s2q18, s2q19_1, s2q19_2, s2q19_3, s2q20_1, s2q20_2, s2q21, s2q22, s2q23, s2q24_a, s2q24_b, s2q24_c, s2q25, s2q25_1, s2q25_2, s2q25_3, s2q26, s2q27, s2q28, s2q29, s2q30, s2q31, s2q32, s2q33, s2q34, s2q35, s2q36, s2q37, s2q38, s2q39, s2q40, s2q41, s2q42, s2q43, s2q44, s2q45, s2q46, s2q47, s2q48, s2q49, s2q50, s3q1, s3q3, s3q7, s3q9, s3q16, s3q17, s3q18, s3q19, s4q1, s4q2, s4q3, s4q4, s4q6, s4q8, s4q9, s4q10_1, s4q11_1, s4q12_1, s4q14, s4q15, s5q12, plot_weight]

[96 rows x 0 columns]

In [27]:

df = final_cleaned_datasets["sas_2024_seasonA_production"]

print("Dataset shape:", df.shape)
print("\nFirst 20 column names:")
print(df.columns.tolist()[:20])

print("\nID column exists:", "id" in df.columns)

if "id" in df.columns:
    print("\nID data type:", df["id"].dtype)
    print("Matching records:")
    display(df.loc[df["id"].astype(str).isin(["740", "743"])].head())

Dataset shape: (39330, 96)

First 20 column names:
['id', 'Segment_ID', 's1q1', 's1q2', 's1q3', 's1q4', 's1q6', 's1q7', 's1q8', 's1q9', 's1q14', 's2q1', 's2q2', 's2q3', 's2q4', 's2q4_o', 'CropCategory', 's2q5', 's2q6', 's2q7']

ID column exists: True

ID data type: object
Matching records:

,id,Segment_ID,s1q1,s1q2,s1q3,s1q4,s1q6,s1q7,s1q8,s1q9,...,s4q6,s4q8,s4q9,s4q10_1,s4q11_1,s4q12_1,s4q14,s4q15,s5q12,plot_weight
739,740,52022,East,Nyagatare,Large Scale Farmer/LSF,22,22,Large scale farmer as Coperative/Company/Asso...,<NA>,<NA>,...,Yes,Yes,Yes,No,Yes,No,Yes,No,05/03/2024,1
742,743,52022,East,Nyagatare,Large Scale Farmer/LSF,22,22,Large scale farmer as Coperative/Company/Asso...,<NA>,<NA>,...,Yes,Yes,No,<NA>,<NA>,<NA>,Yes,Yes,05/03/2024,1

In [28]:

df = final_cleaned_datasets["sas_2024_seasonA_production"]

# 1. Check whether any complete rows are identical
exact_duplicates = df.duplicated(keep=False)
print("Rows involved in exact duplicates:", int(exact_duplicates.sum()))
print("Number of duplicate rows after the first occurrence:",
      int(df.duplicated().sum()))

# 2. Check whether the ID field is unique
print("Total rows:", len(df))
print("Unique IDs:", df["id"].nunique(dropna=True))
print("Missing IDs:", int(df["id"].isna().sum()))
print("Repeated IDs:", int(df["id"].duplicated(keep=False).sum()
                            - df["id"].isna().sum()))

# 3. Inspect repeated IDs, if any
repeated_ids = df.loc[
    df["id"].duplicated(keep=False)
].sort_values("id")

if not repeated_ids.empty:
    display(repeated_ids[["id", "Segment_ID", "s1q1", "s1q2",
                          "s2q4", "CropCategory"]].head(20))

Rows involved in exact duplicates: 0
Number of duplicate rows after the first occurrence: 0
Total rows: 39330
Unique IDs: 39330
Missing IDs: 0
Repeated IDs: 0

In [29]:

import pandas as pd

for name, df in final_cleaned_datasets.items():
    if "production" not in name.lower():
        continue

    print(f"\n{'=' * 65}")
    print(f"DATASET: {name}")
    print(f"{'=' * 65}")

    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Missing IDs:", int(df["id"].isna().sum())
          if "id" in df.columns else "ID column missing")
    print("Unique IDs:", df["id"].nunique(dropna=True)
          if "id" in df.columns else "N/A")
    print("Repeated IDs:",
          int(df["id"].duplicated(keep=False).sum())
          if "id" in df.columns else "N/A")
    print("Exact duplicate rows:", int(df.duplicated().sum()))

=================================================================
DATASET: sas_2024_seasonA_production
=================================================================
Rows: 39330
Columns: 96
Missing IDs: 0
Unique IDs: 39330
Repeated IDs: 0
Exact duplicate rows: 0

=================================================================
DATASET: sas_2024_seasonB_production
=================================================================
Rows: 35584
Columns: 98
Missing IDs: 0
Unique IDs: 35584
Repeated IDs: 0
Exact duplicate rows: 0

=================================================================
DATASET: sas_2024_seasonC_production
=================================================================
Rows: 1949
Columns: 97
Missing IDs: 0
Unique IDs: 1949
Repeated IDs: 0
Exact duplicate rows: 0

In [30]:

import pandas as pd

production_datasets = {
    name: df
    for name, df in final_cleaned_datasets.items()
    if "production" in name.lower()
}

for name, df in production_datasets.items():
    print(f"\n{'=' * 75}")
    print(f"DATASET: {name}")
    print(f"{'=' * 75}")

    report = pd.DataFrame({
        "Data_Type": df.dtypes.astype(str),
        "Missing_Count": df.isna().sum(),
        "Missing_Percent": (df.isna().mean() * 100).round(2),
        "Unique_Values": df.nunique(dropna=True)
    })

    report = report.sort_values(
        ["Missing_Percent", "Unique_Values"],
        ascending=[False, True]
    )

    display(report.head(25))

===========================================================================
DATASET: sas_2024_seasonA_production
===========================================================================

        Data_Type  Missing_Count  Missing_Percent  Unique_Values
s2q10_o    object          39252            99.80             53
s2q4_o     object          39236            99.76             40
s4q10_1    object          39116            99.46              2
s4q11_1    object          39116            99.46              2
s4q12_1    object          39116            99.46              2
s3q17      object          39057            99.31              2
s4q9       object          38933            98.99              2
s2q37      object          37732            95.94              7
s2q24_c    object          37524            95.41             19
s4q15      object          36537            92.90              2
s2q18      object          33305            84.68            683
s2q17      object          33236            84.51            413
s2q16_2    object          33236            84.51            446
s2q16_1    object          33119            84.21              4
s2q10      object          32488            82.60              7
s2q24_b    object          31053            78.95             21
s2q6       object          30101            76.53            898
s2q15      object          27713            70.46            500
s2q5       object          26772            68.07           2131
s3q19      object          24604            62.56              2
s2q27      object          23471            59.68              4
s2q28      object          21006            53.41            307
s2q14      object          19459            49.48            466
s2q13_2    object          19451            49.46           1257
s2q13_1    object          15766            40.09              4

===========================================================================
DATASET: sas_2024_seasonB_production
===========================================================================

        Data_Type  Missing_Count  Missing_Percent  Unique_Values
s2q10_o    object          35522            99.83             42
s2q4_o     object          35496            99.75             33
s4q12_1    object          35398            99.48              2
s4q10_1    object          35394            99.47              1
s4q11_1    object          35394            99.47              2
s3q17      object          35321            99.26              2
s4q9       object          35233            99.01              2
s1q17_o    object          35170            98.84             60
s2q37      object          34612            97.27              5
s2q24_c    object          33295            93.57             20
s2q18      object          32994            92.72            473
s2q17      object          32927            92.53            255
s2q16_2    object          32927            92.53            297
s2q16_1    object          32862            92.35              4
s2q10      object          32492            91.31              7
s4q15      object          31271            87.88              2
s2q15      object          26558            74.63            438
s2q24_b    object          25874            72.71             22
s3q19      object          25550            71.80              2
s1q17      object          25286            71.06              8
s2q6       object          23343            65.60            993
s2q5       object          22814            64.11           1413
s2q14      object          19706            55.38            374
s2q13_2    object          19701            55.36            766
s3q9       object          18122            50.93              2

===========================================================================
DATASET: sas_2024_seasonC_production
===========================================================================

        Data_Type  Missing_Count  Missing_Percent  Unique_Values
s4q10_1    object           1948            99.95              1
s4q11_1    object           1948            99.95              1
s4q12_1    object           1948            99.95              1
s2q4_o     object           1945            99.79              3
s4q9       object           1944            99.74              2
s1q17_o    object           1942            99.64              4
s2q10_o    object           1938            99.44             10
s2q37      object           1930            99.03              2
s3q17      object           1917            98.36              2
s2q24_c    object           1803            92.51             14
s2q17      object           1644            84.35             60
s2q16_2    object           1644            84.35             61
s2q18      object           1623            83.27            128
s2q16_1    object           1617            82.97              3
s2q10      object           1610            82.61              7
s1q17      object           1522            78.09              6
s2q24_b    object           1356            69.57             18
s2q14      object           1132            58.08            152
s2q13_2    object           1131            58.03            225
s4q15      object            736            37.76              2
s3q19      object            731            37.51              2
s3q9       object            711            36.48              2
s2q15      object            684            35.09            197
s2q27      object            628            32.22              4
s2q28      object            587            30.12            123

In [31]:

import pandas as pd

for name, df in final_cleaned_datasets.items():
    if "production" not in name.lower():
        continue

    missing_pct = df.isna().mean() * 100

    summary = pd.DataFrame({
        "Missing_Percent": missing_pct.round(2),
        "Observed_Count": df.notna().sum(),
        "Unique_Observed": df.nunique(dropna=True)
    })

    print(f"\n{'=' * 70}")
    print(name)
    print(f"{'=' * 70}")

    print("Columns 100% missing:", int((missing_pct == 100).sum()))
    print("Columns over 95% missing:", int((missing_pct > 95).sum()))
    print("Columns with at least 80% observed:",
          int((missing_pct <= 20).sum()))

    # Show fields with at least 20% observed data
    display(
        summary.loc[missing_pct <= 80]
        .sort_values("Missing_Percent")
    )

======================================================================
sas_2024_seasonA_production
======================================================================
Columns 100% missing: 0
Columns over 95% missing: 9
Columns with at least 80% observed: 68

            Missing_Percent  Observed_Count  Unique_Observed
id                     0.00           39330            39330
Segment_ID             0.00           39330             1545
s1q1                   0.00           39330                5
s1q2                   0.00           39330               30
s1q3                   0.00           39330                5
...                     ...             ...              ...
s3q19                 62.56           14726                2
s2q5                  68.07           12558             2131
s2q15                 70.46           11617              500
s2q6                  76.53            9229              898
s2q24_b               78.95            8277               21

[81 rows x 3 columns]

======================================================================
sas_2024_seasonB_production
======================================================================
Columns 100% missing: 0
Columns over 95% missing: 9
Columns with at least 80% observed: 68

            Missing_Percent  Observed_Count  Unique_Observed
id                     0.00           35584            35584
Segment_ID             0.00           35584             1509
s1q1                   0.00           35584                5
s1q2                   0.00           35584               30
s1q3                   0.00           35584                5
...                     ...             ...              ...
s2q6                  65.60           12241              993
s1q17                 71.06           10298                8
s3q19                 71.80           10034                2
s2q24_b               72.71            9710               22
s2q15                 74.63            9026              438

[82 rows x 3 columns]

======================================================================
sas_2024_seasonC_production
======================================================================
Columns 100% missing: 0
Columns over 95% missing: 9
Columns with at least 80% observed: 71

            Missing_Percent  Observed_Count  Unique_Observed
id                     0.00            1949             1949
Segment_ID             0.00            1949              555
s1q1                   0.00            1949                5
s1q2                   0.00            1949               30
s1q3                   0.00            1949                2
...                     ...             ...              ...
s4q15                 37.76            1213                2
s2q13_2               58.03             818              225
s2q14                 58.08             817              152
s2q24_b               69.57             593               18
s1q17                 78.09             427                6

[82 rows x 3 columns]

In [32]:

import pandas as pd
from pathlib import Path

reports = []

for name, df in final_cleaned_datasets.items():
    if "production" not in name.lower():
        continue

    for col in df.columns:
        missing_count = int(df[col].isna().sum())

        reports.append({
            "Dataset": name,
            "Variable": col,
            "Data_Type": str(df[col].dtype),
            "Total_Rows": len(df),
            "Missing_Count": missing_count,
            "Missing_Percent": round(
                df[col].isna().mean() * 100, 2
            ),
            "Observed_Count": int(df[col].notna().sum()),
            "Unique_Observed": int(df[col].nunique(dropna=True))
        })

missingness_report = pd.DataFrame(reports)

missingness_report = missingness_report.sort_values(
    ["Dataset", "Missing_Percent"],
    ascending=[True, False]
)

output_path = "/content/production_missingness_report.csv"
missingness_report.to_csv(output_path, index=False)

print("Report rows:", len(missingness_report))
print("Saved to:", output_path)

display(missingness_report.head(15))

from google.colab import files
files.download(output_path)

Report rows: 291
Saved to: /content/production_missingness_report.csv

,Dataset,Variable,Data_Type,Total_Rows,Missing_Count,Missing_Percent,Observed_Count,Unique_Observed
23,sas_2024_seasonA_production,s2q10_o,object,39330,39252,99.80,78,53
15,sas_2024_seasonA_production,s2q4_o,object,39330,39236,99.76,94,40
89,sas_2024_seasonA_production,s4q10_1,object,39330,39116,99.46,214,2
90,sas_2024_seasonA_production,s4q11_1,object,39330,39116,99.46,214,2
91,sas_2024_seasonA_production,s4q12_1,object,39330,39116,99.46,214,2
79,sas_2024_seasonA_production,s3q17,object,39330,39057,99.31,273,2
88,sas_2024_seasonA_production,s4q9,object,39330,38933,98.99,397,2
60,sas_2024_seasonA_production,s2q37,object,39330,37732,95.94,1598,7
44,sas_2024_seasonA_production,s2q24_c,object,39330,37524,95.41,1806,19
93,sas_2024_seasonA_production,s4q15,object,39330,36537,92.90,2793,2
33,sas_2024_seasonA_production,s2q18,object,39330,33305,84.68,6025,683
31,sas_2024_seasonA_production,s2q16_2,object,39330,33236,84.51,6094,446
32,sas_2024_seasonA_production,s2q17,object,39330,33236,84.51,6094,413
30,sas_2024_seasonA_production,s2q16_1,object,39330,33119,84.21,6211,4
22,sas_2024_seasonA_production,s2q10,object,39330,32488,82.60,6842,7

In [33]:

import pandas as pd

# Keep variables with at least 80% observed values
usable_variables = missingness_report[
    missingness_report["Missing_Percent"] <= 20
].copy()

for dataset_name in usable_variables["Dataset"].unique():
    subset = usable_variables[
        usable_variables["Dataset"] == dataset_name
    ].sort_values("Missing_Percent")

    print(f"\n{'=' * 80}")
    print(f"DATASET: {dataset_name}")
    print(f"Variables with at least 80% observed values: {len(subset)}")
    print("=" * 80)

    display(subset[
        [
            "Variable",
            "Data_Type",
            "Missing_Percent",
            "Observed_Count",
            "Unique_Observed"
        ]
    ].reset_index(drop=True))

# Save the filtered report
usable_variables.to_csv(
    "/content/production_usable_variables.csv",
    index=False
)

print("\nSaved: /content/production_usable_variables.csv")

================================================================================
DATASET: sas_2024_seasonA_production
Variables with at least 80% observed values: 68
================================================================================

        Variable Data_Type  Missing_Percent  Observed_Count  Unique_Observed
0           s2q2    object             0.00           39330            17825
1           s2q3    object             0.00           39330                7
2           s2q4    object             0.00           39330               79
3   CropCategory    object             0.00           39330               21
4           s2q7    object             0.00           39330               11
..           ...       ...              ...             ...              ...
63       s2q19_1    object            12.66           34349                4
64         s2q50    object            12.66           34349               46
65         s2q49    object            12.66           34349               52
66         s2q23    object            12.82           34286                7
67         s2q25    object            14.45           33648              661

[68 rows x 5 columns]

================================================================================
DATASET: sas_2024_seasonB_production
Variables with at least 80% observed values: 68
================================================================================

   Variable Data_Type  Missing_Percent  Observed_Count  Unique_Observed
0      s1q6    object             0.00           35584               51
1      s1q7    object             0.00           35584                4
2      s2q1    object             0.00           35584               76
3      s2q2    object             0.00           35584            17256
4      s2q3    object             0.00           35584                7
..      ...       ...              ...             ...              ...
63  s2q20_2    object             2.55           34678             1191
64    s2q25    object             2.69           34628              767
65    s2q23    object             2.72           34615                7
66     s4q3    object            10.85           31723                2
67     s3q3    object            19.17           28764                2

[68 rows x 5 columns]

================================================================================
DATASET: sas_2024_seasonC_production
Variables with at least 80% observed values: 71
================================================================================

      Variable Data_Type  Missing_Percent  Observed_Count  Unique_Observed
0         s1q2    object             0.00            1949               30
1         s1q6    object             0.00            1949               26
2         s1q3    object             0.00            1949                2
3         s1q4    object             0.00            1949               53
4   Segment_ID    object             0.00            1949              555
..         ...       ...              ...             ...              ...
66        s4q3    object             7.39            1805                2
67        s4q4    object            15.75            1642                2
68     s2q24_a    object            15.75            1642               21
69     s2q13_1    object            17.39            1610                3
70        s3q3    object            19.75            1564                2

[71 rows x 5 columns]

Saved: /content/production_usable_variables.csv

In [34]:

import pandas as pd
from IPython.display import display

candidate_variables = [
    "s1q1", "s1q2", "s1q3", "s1q6", "s1q7",
    "s2q2", "s2q3", "s2q4", "CropCategory",
    "s2q13_1", "s2q13_2", "s2q14", "s2q15",
    "s2q16_1", "s2q16_2", "s2q17", "s2q18",
    "s2q19_1", "s2q19_2", "s2q19_3",
    "s2q20_1", "s2q20_2", "s2q21", "s2q22",
    "s2q23", "s2q25", "s2q27", "s2q37",
    "s2q46", "s2q47", "s2q48", "s2q49", "s2q50",
    "s3q3", "s3q7", "s4q3", "plot_weight"
]

for name, df in final_cleaned_datasets.items():
    if "production" not in name.lower():
        continue

    print(f"\n{'=' * 90}")
    print(name)
    print("=" * 90)

    rows = []

    for col in candidate_variables:
        if col not in df.columns:
            continue

        values = df[col].dropna()
        examples = values.astype(str).drop_duplicates().head(8).tolist()

        rows.append({
            "Variable": col,
            "Data_Type": str(df[col].dtype),
            "Observed": int(values.size),
            "Unique": int(values.nunique()),
            "Example_Values": " | ".join(examples)
        })

    display(pd.DataFrame(rows).reset_index(drop=True))

==========================================================================================
sas_2024_seasonA_production
==========================================================================================

,Variable,Data_Type,Observed,Unique,Example_Values
0,s1q1,object,39330,5,Kigali | South | West | North | East
1,s1q2,object,39330,30,Gasabo | Kicukiro | Nyanza | Gisagara | Nyarug...
2,s1q3,object,39330,5,Large Scale Farmer/LSF | Agricultural land on ...
3,s1q6,object,39330,61,1 | 3 | 5 | 2 | 9 | 10 | 13 | 17
4,s1q7,object,39330,4,Large scale farmer as individual | Large scale...
5,s2q2,object,39330,17825,69335.672 | 338740.53 | 12496.678 | 513.396 | ...
6,s2q3,object,39330,7,1 | 2 | 3 | 4 | 5 | 6 | 7
7,s2q4,object,39330,79,Napia grass for fodder | Maize for fodder | Mu...
8,CropCategory,object,39330,21,Fodder crops | Maize | Other crops | Vegetable...
9,s2q13_1,object,23564,4,Kg | Not applicable (NA) | Cuttings | g
10,s2q13_2,object,19879,1257,20 | 30 | 15 | 26 | 11 | 1 | 5 | 4
11,s2q14,object,19871,466,0 | 15 | 10 | 2839.9 | 1529.1 | 3674.7 | 1237....
12,s2q15,object,11617,500,0 | 22500 | 15000 | 4240147 | 999 | 3683900 | ...
13,s2q16_1,object,6211,4,Kg | Not applicable (NA) | g | Cuttings
14,s2q16_2,object,6094,446,1360 | 1 | 7 | 20 | 518.75 | 208.8 | 13 | 8
15,s2q17,object,6094,413,1360 | 1 | 7 | 20 | 518.75 | 208.8 | 13 | 8
16,s2q18,object,6025,683,1360000 | 700 | 4900 | 20000 | 518750 | 208800...
17,s2q19_1,object,34349,4,Kg | Bundle/Bulk | Stems/leaves | Pieces/Numbers
18,s2q19_2,object,34349,2006,173325 | 951583 | 0 | 6 | 70 | 12754 | 16188 |...
19,s2q19_3,object,34349,2084,173325 | 951583 | 0 | 6 | 70 | 12754 | 16188 |...
20,s2q20_1,object,34349,936,0 | 19401 | 1000 | 22 | 4000 | 120000 | 500 | ...
21,s2q20_2,object,34349,963,0 | 19401 | 1000 | 22 | 4000 | 120000 | 500 | ...
22,s2q21,object,34349,2382,173325 | 951583 | 19401 | 6 | 70 | 12754 | 161...
23,s2q22,object,34349,2546,173325 | 964337 | 38378 | 1700 | 16188 | 3500 ...
24,s2q23,object,34286,7,No change | Was increased | Was highly decreas...
25,s2q25,object,33648,661,0 | 6240 | 1000 | 200 | 1594 | 1814 | 70 | 10000
26,s2q27,object,15859,4,Cooperative/company/Association | Farm/Home | ...
27,s2q37,object,1598,7,Own storage | Storage owned by Cooperatives/pr...
28,s2q46,object,34349,73,0 | 20 | 94 | 50 | 200 | 100 | 1460 | 500
29,s2q47,object,34349,85,0 | -340 | -1 | 100 | 300 | 700 | 200 | 1350
30,s2q48,object,34349,119,0 | 8 | 360 | 430 | 250 | 300 | 106 | 200
31,s2q49,object,34349,52,0 | 100 | 20 | 240 | 600 | 700 | 403 | 1595
32,s2q50,object,34349,46,0 | 20 | 100 | 30 | 1500 | 8740 | 10000 | 400
33,s3q3,object,35344,2,Yes | No
34,s3q7,object,39330,2,No | Yes
35,s4q3,object,35563,2,Yes | No
36,plot_weight,object,39330,16383,1 | 141.3141 | 60.13324 | 118.4835 | 624.593 |...

==========================================================================================
sas_2024_seasonB_production
==========================================================================================

,Variable,Data_Type,Observed,Unique,Example_Values
0,s1q1,object,35584,5,Kigali | South | West | North | East
1,s1q2,object,35584,30,Gasabo | Kicukiro | Nyanza | Gisagara | Nyarug...
2,s1q3,object,35584,5,Large Scale Farmer/LSF | Agricultural land on ...
3,s1q6,object,35584,51,55 | 3 | 4 | 7 | 17 | 9 | 10 | 11
4,s1q7,object,35584,4,Large scale farmer as individual | Large scale...
5,s2q2,object,35584,17256,172737.17 | 130199.2 | 29915.363 | 92041.133 |...
6,s2q3,object,35584,7,1 | 3 | 2 | 4 | 5 | 6 | 7
7,s2q4,object,35584,78,Maize for fodder | Soybean for fodder | Other ...
8,CropCategory,object,35584,21,Fodder crops | Other crops | Vegetables | Maiz...
9,s2q13_1,object,18858,4,Not applicable (NA) | Kg | g | Cuttings
10,s2q13_2,object,15883,766,2 | 78 | 15 | 4 | 7 | 5 | 13500 | 86
11,s2q14,object,15878,374,0 | 86 | 6 | 78 | 220 | 130 | 7200 | 3184.05
12,s2q15,object,9026,438,0 | 60200 | 4200 | 54600 | 154000 | 20000 | 10...
13,s2q16_1,object,2722,4,Kg | g | Cuttings | Not applicable (NA)
14,s2q16_2,object,2657,297,350 | 320 | 100 | 70 | 160 | 7 | 12 | 25
15,s2q17,object,2657,255,0 | 320 | 350 | 100 | 160 | 12 | 25 | 800
16,s2q18,object,2590,473,640000 | 80500 | 75000 | 320000 | 24000 | 5000...
17,s2q19_1,object,34679,4,Kg | Stems/leaves | Bundle/Bulk | Pieces/Numbers
18,s2q19_2,object,34678,1611,72000 | 7800 | 50000 | 1100 | 380 | 12000 | 30...
19,s2q19_3,object,34678,1670,72000 | 7800 | 50000 | 1100 | 380 | 12000 | 30...
20,s2q20_1,object,34678,1151,0 | 500 | 100 | 20 | 3000 | 8000 | 5500 | 250
21,s2q20_2,object,34678,1191,0 | 500 | 100 | 20 | 3000 | 8000 | 5500 | 250
22,s2q21,object,34679,2169,72000 | 7800 | 50500 | 1200 | 400 | 12000 | 30...
23,s2q22,object,34679,2368,313220 | 16000 | 50500 | 1200 | 400 | 60000 | ...
24,s2q23,object,34615,7,No change | Was decreased | Was increased | Wa...
25,s2q25,object,34628,767,313000 | 15990 | 0 | 1170 | 50 | 250 | 100 | 9000
26,s2q27,object,17658,4,Market | Cooperative/company/Association | Far...
27,s2q37,object,972,5,Own storage | Storage owned by Cooperatives/pr...
28,s2q46,object,34679,53,50 | 5 | 0 | 15 | 6 | 25 | 2 | 10
29,s2q47,object,34679,80,0 | 3 | -2 | -1 | 69 | 40 | 88 | 25
30,s2q48,object,34679,81,0 | 5 | 50 | 45 | 10 | 1000 | 1 | 924
31,s2q49,object,34679,36,50 | 0 | 2 | 10 | 25 | 100 | 229 | 105
32,s2q50,object,34679,39,0 | 25 | 1 | 5 | 2 | 7500 | 2190 | 450
33,s3q3,object,28764,2,Yes | No
34,s3q7,object,35583,2,Yes | No
35,s4q3,object,31723,2,Yes | No
36,plot_weight,object,35584,16267,1 | 141.258 | 54.78037 | 108.934 | 724.0408 | ...

==========================================================================================
sas_2024_seasonC_production
==========================================================================================

,Variable,Data_Type,Observed,Unique,Example_Values
0,s1q1,object,1949,5,Kigali | South | West | North | East
1,s1q2,object,1949,30,Nyarugenge | Gasabo | Kicukiro | Nyanza | Gisa...
2,s1q3,object,1949,2,Agricultural land on hillside | Agricultural ...
3,s1q6,object,1949,26,1 | 2 | 3 | 4 | 5 | 6 | 7 | 9
4,s1q7,object,1949,2,Small scale farmer as individual | Small Scale...
5,s2q2,object,1949,1632,956.85834 | 1570.7994 | 800.91815 | 1190.3546 ...
6,s2q3,object,1949,4,3 | 4 | 1 | 2
7,s2q4,object,1949,25,Soybean | Bush bean | Sweet potato | Irish pot...
8,CropCategory,object,1949,9,Soybean | Bush bean | Sweet potato | Irish pot...
9,s2q13_1,object,1610,3,Kg | Not applicable (NA) | g
10,s2q13_2,object,818,225,2 | 7.3 | 4.5 | 6 | 6.2 | 9.1 | 7 | 7.2
11,s2q14,object,817,152,2 | 5.5 | 0 | 6 | 4.5 | 9.1 | 0.5 | 7.2
12,s2q15,object,1265,197,2000 | 6600 | 7200 | 4500 | 1400 | 36000 | 500...
13,s2q16_1,object,332,3,g | Not applicable (NA) | Kg
14,s2q16_2,object,305,61,150 | 100 | 375 | 50 | 15 | 30 | 125 | 40
15,s2q17,object,305,60,150 | 100 | 375 | 50 | 15 | 30 | 0 | 40
16,s2q18,object,326,128,25500 | 5400 | 18000 | 14000 | 20000 | 12000 |...
17,s2q19_1,object,1949,4,Kg | Bundle/Bulk | Stems/leaves | Pieces/Numbers
18,s2q19_2,object,1949,389,0 | 21 | 22 | 6 | 51 | 70 | 8 | 94
19,s2q19_3,object,1949,383,0 | 21 | 22 | 6 | 51 | 70 | 8 | 94
20,s2q20_1,object,1949,312,15 | 28 | 49 | 45 | 13 | 21 | 50 | 10
21,s2q20_2,object,1949,314,15 | 28 | 49 | 45 | 13 | 21 | 50 | 10
22,s2q21,object,1949,542,15 | 49 | 67 | 19 | 21 | 101 | 10 | 70
23,s2q22,object,1949,543,25 | 49 | 85 | 95 | 19 | 78 | 101 | 10
24,s2q23,object,1935,7,No change | Was decreased | Was increased | Wa...
25,s2q25,object,1936,23,20 | 0 | 19 | 38 | 10 | 24 | 30 | 40
26,s2q27,object,1321,4,Market | Farm/Home | Other selling place | Coo...
27,s2q37,object,19,2,Own storage | Storage owned by Cooperatives/pr...
28,s2q46,object,1949,26,0 | 15 | 30 | 50 | 2 | 1 | 3 | 45
29,s2q47,object,1949,17,0 | -1 | 150 | 20 | 70 | 5 | 72 | 7
30,s2q48,object,1949,13,0 | 1 | 8 | 50 | 240 | 2 | 7 | 20
31,s2q49,object,1949,21,0 | 5 | 40 | 30 | 8 | 98 | 10 | 12
32,s2q50,object,1949,24,0 | 17 | 20 | 1 | 6 | 3 | 674 | 30
33,s3q3,object,1564,2,No | Yes
34,s3q7,object,1949,2,No | Yes
35,s4q3,object,1805,2,Yes | No
36,plot_weight,object,1949,1632,36.229675 | 22.069442 | 43.283657 | 29.122975 ...